Repository DataDog/integrations-extras, pull requests merged in 2018-08, with the labels that each got.

#182 Removing wrong cat
  portworx/manifest.json
Labels: changelog/no-changelog, documentation

#184 Fixing non ASCII character
  .github/PULL_REQUEST_TEMPLATE.md
  convox/README.md
  rookout/README.md
Labels: changelog/no-changelog, documentation

#191 Update ci to use the dev package
  .travis.yml
  appveyor.yml
  requirements-dev.txt
Labels: dev/testing

#196 Update datadog-checks-base dependency
  appveyor.yml
  reboot_required/requirements.in
  reboot_required/requirements.txt
  reboot_required/tox.ini
  sortdb/requirements.in
  sortdb/requirements.txt
  sortdb/tox.ini
  traefik/tox.ini
Labels: dev/testing

#202 Fixing title
  logstash/README.md
Labels: changelog/no-changelog, documentation

#203 Gremlin resolve image size for tile
  gremlin/images/events-overlay.png
Labels: changelog/no-changelog, integration/gremlin
