Repository DataDog/integrations-extras, pull requests merged in 2018-06, with the labels that each got.

#146 Fixing list layout
  reboot_required/README.md
Labels: doc

#153 Moving inline links to reference link
  ambassador/README.md
  buddy/README.md
  convox/README.md
  gnatsd/README.md
  gnatsd_streaming/README.md
  logstash/README.md
  logzio/README.md
  nomad/README.md
  rbltracker/README.md
  split/README.md
  uptime/README.md
  vns3/README.md
Labels: doc

#157 Cleanup stale files, update github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  circle.yml
Labels: dev/testing, dev/tooling

#156 Revamp the CI
  .travis.yml
  README.md
  appveyor.yml
  requirements-dev.txt
  tasks/__init__.py
  tasks/changelog.py
  tasks/cleanup.py
  tasks/constants.py
  tasks/manifest.py
  tasks/release.py
  tasks/test.py
  tasks/upgrade.py
  tasks/utils/__init__.py
  tasks/utils/common.py
  tasks/utils/git.py
  tasks/utils/github.py
Labels: dev/testing, dev/tooling

#155 Update to new wheel format and tests
  .gitignore
  .travis.yml
  reboot_required/CHANGELOG.md
  reboot_required/MANIFEST.in
  reboot_required/README.md
  reboot_required/ci/reboot_required.rake
  reboot_required/datadog_checks/__init__.py
  reboot_required/datadog_checks/reboot_required/__about__.py
  reboot_required/datadog_checks/reboot_required/__init__.py
  reboot_required/datadog_checks/reboot_required/reboot_required.py
  reboot_required/manifest.json
  reboot_required/requirements-dev.txt
  reboot_required/requirements.in
  reboot_required/requirements.txt
  reboot_required/setup.py
  reboot_required/test_reboot_required.py
  reboot_required/tests/__init__.py
  reboot_required/tests/common.py
  reboot_required/tests/test_reboot_required.py
  reboot_required/tox.ini
  tasks/constants.py
Labels: changelog/Changed, integration/reboot_required

#159 Release preparation
  reboot_required/MANIFEST.in
  reboot_required/datadog_checks/reboot_required/data/conf.yaml.example
  reboot_required/datadog_checks/reboot_required/reboot_required.py
  reboot_required/requirements.in
  reboot_required/requirements.txt
  reboot_required/setup.py
  reboot_required/tests/common.py
  reboot_required/tests/test_reboot_required.py
Labels: changelog/no-changelog, integration/reboot_required

#158 Changes for supporting Sortdb
  .travis.yml
  sortdb/CHANGELOG.md
  sortdb/MANIFEST.in
  sortdb/README.md
  sortdb/datadog_checks/__init__.py
  sortdb/datadog_checks/sortdb/__about__.py
  sortdb/datadog_checks/sortdb/__init__.py
  sortdb/datadog_checks/sortdb/check.py
  sortdb/datadog_checks/sortdb/data/conf.yaml.example
  sortdb/manifest.json
  sortdb/metadata.csv
  sortdb/requirements-dev.txt
  sortdb/requirements.in
  sortdb/requirements.txt
  sortdb/setup.py
  sortdb/tests/__init__.py
  sortdb/tests/sortdb_metrics.json
  sortdb/tests/test_sortdb.py
  sortdb/tox.ini
  tasks/constants.py
Labels: changelog/Added, integration/sortdb

#161 Fix ensure current branch is not master
  tasks/utils/git.py
Labels: dev/tooling

#165 Removing useless comma
  gnatsd/service_check.json
  gnatsd_streaming/service_check.json
  logstash/service_checks.json
  neo4j/service_checks.json
  reboot_required/service_checks.json
  redis_sentinel/service_checks.json
  snmpwalk/service_checks.json
  sortdb/service_checks.json
  storm/service_checks.json
Labels: changelog/no-changelog, documentation

#164 Link fix
  reboot_required/README.md
Labels: changelog/no-changelog, documentation
