Repository DataDog/integrations-extras, pull requests merged in 2019-02, with the labels that each got.

#336 [reboot_required] fix link to sample conf file
  reboot_required/README.md
Labels: changelog/no-changelog, documentation, integration/reboot_required

#339 Add category for riak_repl
  riak_repl/manifest.json
Labels: changelog/no-changelog

#334 Update logstash instruction with proxy elements
  logstash/README.md
Labels: changelog/no-changelog, documentation, integration/logstash

#343 Refactoring nextcloud configuration file
  nextcloud/datadog_checks/nextcloud/data/conf.yaml.example
Labels: changelog/no-changelog, documentation

#344 Fix hbase regionserver docs
  hbase_regionserver/README.md
Labels: documentation
