Repository DataDog/integrations-extras, pull requests merged in 2020-04, with the labels that each got.

#576 Add `tls_host_header` and `kerberos_cache` config options
  pihole/datadog_checks/pihole/data/conf.yaml.example
Labels: changelog/Fixed, integration/pihole

#577 Fix metric_to_check for all integrations
  ambassador/manifest.json
  rbltracker/manifest.json
  resin/manifest.json
  sigsci/manifest.json
  sigsci/metadata.csv
Labels: changelog/no-changelog, integration/ambassador, integration/rbltracker, integration/sigsci

#575 Updating ConfigCat readme
  configcat/README.md
Labels: changelog/no-changelog, documentation

#579 Add Rundeck integration tile
  rundeck/CHANGELOG.md
  rundeck/README.md
  rundeck/assets/images/dd-search.png
  rundeck/assets/images/rundeck-setup.png
  rundeck/assets/images/webhook-fill.png
  rundeck/assets/images/webhooks-config.png
  rundeck/assets/logos/avatars-bot.png
  rundeck/assets/logos/saas_logos-bot.png
  rundeck/assets/logos/saas_logos-small.png
  rundeck/assets/service_checks.json
  rundeck/manifest.json
  rundeck/metadata.csv
Labels: documentation

#585 removes docs category
  bluematador/manifest.json
Labels: changelog/no-changelog, documentation
