Repository DataDog/integrations-extras, pull requests merged in 2021-12, with the labels that each got.

#1086 fix: Check the value of rt_sink_connected_to is a dict
  riak_repl/CHANGELOG.md
  riak_repl/datadog_checks/riak_repl/__about__.py
  riak_repl/datadog_checks/riak_repl/riak_repl.py
Labels: changelog/Fixed, integration/riak-repl

#1075 Update Tyk manifest for sync
  tyk/manifest.json
Labels: changelog/no-changelog

#950 Add a FoundationDB Integration
  .azure-pipelines/all.yml
  .azure-pipelines/scripts/foundationdb/linux/55_install_client.sh
  .codecov.yml
  .github/CODEOWNERS
  foundationdb/CHANGELOG.md
  foundationdb/MANIFEST.in
  foundationdb/README.md
  foundationdb/assets/configuration/spec.yaml
  foundationdb/assets/dashboards/foundationdb_latency_probe.json
  foundationdb/assets/dashboards/foundationdb_machines_and_processes.json
  foundationdb/assets/dashboards/foundationdb_queues.json
  foundationdb/assets/dashboards/foundationdb_size_and_utilization.json
  foundationdb/assets/dashboards/foundationdb_transactions_and_workload.json
  foundationdb/assets/monitors/conflicts.json
  foundationdb/assets/monitors/errors_logged.json
  foundationdb/assets/monitors/high_durability_lag.json
  foundationdb/assets/monitors/log_queue_spill.json
  foundationdb/assets/monitors/low_disk_space.json
  foundationdb/assets/monitors/read_latency_probe.json
  foundationdb/assets/monitors/rejections.json
  foundationdb/assets/monitors/service_check.json
  foundationdb/assets/monitors/transaction_commit_latency.json
  foundationdb/assets/monitors/transaction_start_latency.json
  foundationdb/assets/saved_views/all.json
  foundationdb/assets/saved_views/errors.json
  foundationdb/assets/saved_views/errors_and_strong_warnings.json
  foundationdb/assets/service_checks.json
  foundationdb/datadog_checks/__init__.py
  foundationdb/datadog_checks/foundationdb/__about__.py
  foundationdb/datadog_checks/foundationdb/__init__.py
  foundationdb/datadog_checks/foundationdb/check.py
  foundationdb/datadog_checks/foundationdb/config_models/__init__.py
  foundationdb/datadog_checks/foundationdb/config_models/defaults.py
  foundationdb/datadog_checks/foundationdb/config_models/instance.py
  foundationdb/datadog_checks/foundationdb/config_models/shared.py
  foundationdb/datadog_checks/foundationdb/config_models/validators.py
  foundationdb/datadog_checks/foundationdb/data/conf.yaml.example
  foundationdb/images/.gitkeep
  foundationdb/manifest.json
  foundationdb/metadata.csv
  foundationdb/requirements-dev.txt
  foundationdb/requirements.in
  foundationdb/setup.py
  foundationdb/tests/__init__.py
  foundationdb/tests/conftest.py
  foundationdb/tests/docker/Dockerfile.fdb-tls
  foundationdb/tests/docker/docker-compose-tls.yaml
  foundationdb/tests/docker/docker-compose.yaml
  foundationdb/tests/docker/fdb.bash
  foundationdb/tests/docker/tls/cert.crt
  foundationdb/tests/docker/tls/fdb.pem
  foundationdb/tests/docker/tls/private.key
  foundationdb/tests/fdb-tls.cluster
  foundationdb/tests/fdb.cluster
  foundationdb/tests/full.json
  foundationdb/tests/partial.json
  foundationdb/tests/test_foundationdb.py
  foundationdb/tox.ini
Labels: kind/new-integration, do-not-merge/HOLD

#1080 LambdaTest integration tile
  .github/CODEOWNERS
  lambdatest/CHANGELOG.md
  lambdatest/README.md
  lambdatest/assets/logos/lambdatest.svg
  lambdatest/assets/logos/lambdatest_white.png
  lambdatest/assets/service_checks.json
  lambdatest/images/.gitkeep
  lambdatest/manifest.json
  lambdatest/metadata.csv
Labels: editorial review
