Repository DataDog/integrations-extras, pull requests merged in 2021-10, with the labels that each got.

#1023 adds harness cloud cost management integration
  .github/CODEOWNERS
  harness_cloud_cost_management/CHANGELOG.md
  harness_cloud_cost_management/README.md
  harness_cloud_cost_management/assets/dashboards/harness_cloud_cost_management_overview.json
  harness_cloud_cost_management/images/ccm_dashboard_on_datadog.png
  harness_cloud_cost_management/images/ccm_dashboard_on_harness.png
  harness_cloud_cost_management/manifest.json
Labels: kind/app

#1021 Pagerduty tile
  .github/CODEOWNERS
  pagerduty/CHANGELOG.md
  pagerduty/README.md
  pagerduty/assets/dashboards/pagerduty_overview.json
  pagerduty/images/.gitkeep
  pagerduty/images/incidents.jpg
  pagerduty/images/landing_page.png
  pagerduty/images/status_dashboard.jpg
  pagerduty/images/status_dashboard2.jpg
  pagerduty/manifest.json
Labels: editorial review, kind/app

#1024 Add Shoreline integration tile
  .github/CODEOWNERS
  shoreline/README.md
  shoreline/assets/.gitkeep
  shoreline/assets/logos/logo.svg
  shoreline/images/.gitkeep
  shoreline/images/automate_remediation.png
  shoreline/images/fleetwide_interactive_debugging_and_repair.png
  shoreline/images/fleetwide_linux_command_details.png
  shoreline/images/integrate_shoreline_and_datadog.png
  shoreline/images/link_icon.svg
  shoreline/images/remediation_dashboard.png
  shoreline/manifest.json
Labels: kind/app

#1050 RedisEnterprise Integration Page Edit
  redisenterprise/README.md
Labels: documentation, changelog/no-changelog
