Repository DataDog/integrations-extras, pull requests merged in 2021-09, with the labels that each got.

#976 Add a Writing Blog Link
  statsig/README.md
Labels: documentation

#978 Use requests wrapper
  aqua/datadog_checks/aqua/aqua.py
Labels: changelog/Added

#980 Do not use legacy signature
  redis_sentinel/datadog_checks/redis_sentinel/redis_sentinel.py
Labels: changelog/no-changelog

#979 snmpwalk legacy signature
  snmpwalk/datadog_checks/snmpwalk/snmpwalk.py
Labels: changelog/no-changelog

#981 Do not use legacy signature
  portworx/datadog_checks/portworx/portworx.py
Labels: changelog/no-changelog

#986 Remove generic tag checking
  filebeat/tox.ini
Labels: changelog/no-changelog, integration/filebeat

#984 DOCS-1135 Update integration install instructions (part 6)
  puma/README.md
  reboot_required/README.md
  redis_sentinel/README.md
  riak_repl/README.md
  sendmail/README.md
Labels: documentation, changelog/no-changelog

#961 Add Cloudsmith Integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  cloudsmith/CHANGELOG.md
  cloudsmith/MANIFEST.in
  cloudsmith/README.md
  cloudsmith/assets/configuration/spec.yaml
  cloudsmith/assets/dashboards/cloudsmith_overview.json
  cloudsmith/assets/service_checks.json
  cloudsmith/datadog_checks/__init__.py
  cloudsmith/datadog_checks/cloudsmith/__about__.py
  cloudsmith/datadog_checks/cloudsmith/__init__.py
  cloudsmith/datadog_checks/cloudsmith/check.py
  cloudsmith/datadog_checks/cloudsmith/data/conf.yaml.example
  cloudsmith/images/.gitkeep
  cloudsmith/manifest.json
  cloudsmith/metadata.csv
  cloudsmith/requirements-dev.txt
  cloudsmith/requirements.in
  cloudsmith/setup.py
  cloudsmith/tests/__init__.py
  cloudsmith/tests/conftest.py
  cloudsmith/tests/test_cloudsmith.py
  cloudsmith/tox.ini
Labels: kind/new-integration, editorial review, integration/cloudsmith

#989 DOCS-1135 Update integration install instructions (part 7)
  snmpwalk/README.md
  sortdb/README.md
  speedtest/README.md
  stardog/README.md
  storm/README.md
Labels: changelog/no-changelog, integration/sortdb, integration/stardog, integration/storm, integration/snmpwalk, integration/speedtest

#994 DOCS-2446 - fixing borked hashes in extras
  filebeat/README.md
  gnatsd_streaming/README.md
  logstash/README.md
  neo4j/README.md
  neutrona/README.md
  sortdb/README.md
  upsc/README.md
Labels: documentation

#983 Move cert-manager dashboard to new dashboards
  cert_manager/assets/dashboards/certmanager_overview.json
  cert_manager/images/overview_dashboard.png
Labels: changelog/no-changelog

#982 Move Gatekeeper dashboard to new dashboard type
  gatekeeper/assets/dashboards/gatekeeper_overview.json
  gatekeeper/images/gatekeeper_dashboard.png
Labels: changelog/no-changelog

#1006 Update style for comments
  eventstore/datadog_checks/eventstore/eventstore.py
  logstash/datadog_checks/logstash/logstash.py
  redisenterprise/datadog_checks/redisenterprise/check.py
Labels: changelog/no-changelog

#972 New Integration Calico
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  calico/CHANGELOG.md
  calico/MANIFEST.in
  calico/README.md
  calico/assets/configuration/spec.yaml
  calico/assets/dashboards/calico_overview.json
  calico/assets/monitors/dataplane_failures.json
  calico/assets/monitors/ipset_error.json
  calico/assets/monitors/iptables_restore_errors.json
  calico/assets/monitors/iptables_save_errors.json
  calico/assets/service_checks.json
  calico/datadog_checks/__init__.py
  calico/datadog_checks/calico/__about__.py
  calico/datadog_checks/calico/__init__.py
  calico/datadog_checks/calico/check.py
  calico/datadog_checks/calico/data/conf.yaml.example
  calico/datadog_checks/calico/metrics.py
  calico/images/.gitkeep
  calico/manifest.json
  calico/metadata.csv
  calico/requirements-dev.txt
  calico/requirements.in
  calico/setup.py
  calico/tests/__init__.py
  calico/tests/common.py
  calico/tests/conftest.py
  calico/tests/felix-service.yaml
  calico/tests/fixtures/calico.txt
  calico/tests/kind-calico.yaml
  calico/tests/test_calico.py
  calico/tests/test_e2e.py
  calico/tests/utils.py
  calico/tox.ini
Labels: kind/new-integration, editorial review, integration/calico

#1009 Sync config models
  cyral/datadog_checks/cyral/data/conf.yaml.example
  eventstore/datadog_checks/eventstore/data/conf.yaml.example
  filebeat/datadog_checks/filebeat/data/conf.yaml.example
  gatekeeper/datadog_checks/gatekeeper/data/auto_conf.yaml
  gatekeeper/datadog_checks/gatekeeper/data/conf.yaml.example
  gnatsd/datadog_checks/gnatsd/data/conf.yaml.example
  gnatsd_streaming/datadog_checks/gnatsd_streaming/data/conf.yaml.example
  jfrog_platform/datadog_checks/jfrog_platform/data/conf.yaml.example
  kernelcare/datadog_checks/kernelcare/data/conf.yaml.example
  logstash/datadog_checks/logstash/data/conf.yaml.example
  neo4j/datadog_checks/neo4j/data/conf.yaml.example
  open_policy_agent/datadog_checks/open_policy_agent/data/auto_conf.yaml
  open_policy_agent/datadog_checks/open_policy_agent/data/conf.yaml.example
  php_apcu/datadog_checks/php_apcu/data/conf.yaml.example
  php_opcache/datadog_checks/php_opcache/data/conf.yaml.example
  pihole/datadog_checks/pihole/data/conf.yaml.example
  pulsar/datadog_checks/pulsar/data/conf.yaml.example
  puma/datadog_checks/puma/data/conf.yaml.example
  redisenterprise/datadog_checks/redisenterprise/data/conf.yaml.example
  tidb/datadog_checks/tidb/data/auto_conf.yaml
  tidb/datadog_checks/tidb/data/conf.yaml.example
  zabbix/datadog_checks/zabbix/data/conf.yaml.example
Labels: changelog/no-changelog

#1012 Sync config file
  calico/datadog_checks/calico/data/conf.yaml.example
Labels: changelog/no-changelog, integration/calico
