Repository DataDog/integrations-extras, pull requests merged in 2022-05, with the labels that each got.

#1293 Add sales email to manifest
  purefa/manifest.json
Labels: changelog/no-changelog, integration/purefa

#1238 Add speedscale integration
  .github/CODEOWNERS
  speedscale/README.md
  speedscale/assets/dashboards/SpeedscaleOverview.json
  speedscale/assets/service_checks.json
  speedscale/images/.gitkeep
  speedscale/images/speedscale-icon.svg
  speedscale/images/speedscale-landscape.svg
  speedscale/manifest.json
  speedscale/metadata.csv
Labels: changelog/Added, kind/new-integration, kind/technology-partner, agent/reviewed, integration/speedscale

#1297 Add back requirements.in
  nvml/requirements.in
Labels: changelog/Added

#1253 Edits to reflect new Sedai logo, marketing content and an out of the box dashboard
  .github/CODEOWNERS
  sedai/README.md
  sedai/assets/dashboards/sedai_overview.json
  sedai/assets/logo.svg
  sedai/images/Add_DataDog_Channel-Working_REC.png
  sedai/images/Add_DataDog_Channel.png
  sedai/images/DataDog_Notification_Integration.png
  sedai/images/Enable_Notifications.png
  sedai/manifest.json
Labels: changelog/no-changelog, kind/technology-partner, agent/reviewed, integration/sedai

#1298 Pin setuptools version
  cert_manager/pyproject.toml
  cyral/pyproject.toml
  filebeat/pyproject.toml
  fluentbit/pyproject.toml
  gatekeeper/pyproject.toml
  gnatsd/pyproject.toml
  gnatsd_streaming/pyproject.toml
  hbase_master/pyproject.toml
  hbase_regionserver/pyproject.toml
  jfrog_platform/pyproject.toml
  kernelcare/pyproject.toml
  lighthouse/pyproject.toml
  logstash/pyproject.toml
  nextcloud/pyproject.toml
  ns1/pyproject.toml
  nvml/pyproject.toml
  octoprint/pyproject.toml
  open_policy_agent/pyproject.toml
  php_apcu/pyproject.toml
  php_opcache/pyproject.toml
  pihole/pyproject.toml
  ping/pyproject.toml
  portworx/pyproject.toml
  pulsar/pyproject.toml
  puma/pyproject.toml
  purefa/pyproject.toml
  purefb/pyproject.toml
  reboot_required/pyproject.toml
  redis_sentinel/pyproject.toml
  redisenterprise/pyproject.toml
  redpanda/pyproject.toml
  resin/pyproject.toml
  riak_repl/pyproject.toml
  sendmail/pyproject.toml
  snmpwalk/pyproject.toml
  sortdb/pyproject.toml
  speedtest/pyproject.toml
  stardog/pyproject.toml
  storm/pyproject.toml
  syncthing/pyproject.toml
  tidb/pyproject.toml
  traefik/pyproject.toml
  unbound/pyproject.toml
  upsc/pyproject.toml
  vespa/pyproject.toml
  zabbix/pyproject.toml
Labels: changelog/no-changelog, dev/tooling

#1123 Enhance Lighthouse Integration - Multiple URLs, Form Factor Configuration, and New Metrics
  lighthouse/datadog_checks/lighthouse/data/conf.yaml.example
  lighthouse/datadog_checks/lighthouse/lighthouse.py
  lighthouse/metadata.csv
  lighthouse/tests/lighthouse_example_valid_response.json
  lighthouse/tests/test_lighthouse.py
Labels: changelog/Added, integration/lighthouse

#1302 Superwise Edit
  superwise/README.md
Labels: documentation

#1309 Fix copypasta error
  zscaler/README.md
Labels: changelog/no-changelog

#1276 Add Zebrium tile
  .github/CODEOWNERS
  zebrium/CHANGELOG.md
  zebrium/README.md
  zebrium/assets/dashboards/root_cause_as_a_service_sample_dashboard.json
  zebrium/assets/logos/Zebrium.svg
  zebrium/assets/service_checks.json
  zebrium/images/Zebrium-Root_Cause_as_a_Service_thumb.png
  zebrium/images/Zebrium_Root_Cause_Finder_Widget.png
  zebrium/images/Zebrium_Root_Cause_Finder_With_Side_Panel.png
  zebrium/manifest.json
  zebrium/metadata.csv
Labels: changelog/Added, editorial review, kind/technology-partner, agent/reviewed, integration/zebrium

#1304 Added Cockroach Cloud integration tile
  .github/CODEOWNERS
  cockroach_cloud/README.md
  cockroach_cloud/assets/dashboards/cockroach_cloud_overview.json
  cockroach_cloud/assets/service_checks.json
  cockroach_cloud/manifest.json
  cockroach_cloud/metadata.csv
Labels: editorial review

#1315 Correct the spelling of Log Explorer
  datazoom/README.md
  datazoom/manifest.json
Labels: changelog/no-changelog

#1324 Fix broken link to api keys
  planetscale/README.md
Labels: documentation
