Repository DataDog/integrations-extras, pull requests merged in 2022-06, with the labels that each got.

#1153 Add `pyproject.toml` file
  cloudsmith/MANIFEST.in
  cloudsmith/pyproject.toml
  cloudsmith/requirements.in
  cloudsmith/setup.py
  cloudsmith/tox.ini
Labels: changelog/Added, integration/cloudsmith

#1149 Add `pyproject.toml` file
  aws_pricing/MANIFEST.in
  aws_pricing/pyproject.toml
  aws_pricing/requirements.in
  aws_pricing/setup.py
  aws_pricing/tox.ini
Labels: changelog/Added, integration/aws_pricing

#1328 Move v2 manifest field `classifier_tags` under `tile`
  apptrail/manifest.json
  data_runner/manifest.json
  embrace_mobile/manifest.json
  eversql/manifest.json
  fairwinds_insights/manifest.json
  finout/manifest.json
  harness_cloud_cost_management/manifest.json
  launchdarkly/manifest.json
  lightstep_incident_response/manifest.json
  pagerduty/manifest.json
  planetscale/manifest.json
  purefa/manifest.json
  purefb/manifest.json
  rookout/manifest.json
  shoreline/manifest.json
  twenty_forty_eight/manifest.json
  zebrium/manifest.json
Labels: do-not-merge/HOLD

#1244 Add initial draft of Netnology's SDWAN Datadog integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  nn_sdwan/CHANGELOG.md
  nn_sdwan/MANIFEST.in
  nn_sdwan/README.md
  nn_sdwan/assets/configuration/spec.yaml
  nn_sdwan/assets/dashboards/nn_sdwan_overview.json
  nn_sdwan/assets/monitors/high-latency-monitor.json
  nn_sdwan/assets/monitors/packet-loss-monitor.json
  nn_sdwan/assets/service_checks.json
  nn_sdwan/datadog_checks/__init__.py
  nn_sdwan/datadog_checks/nn_sdwan/__about__.py
  nn_sdwan/datadog_checks/nn_sdwan/__init__.py
  nn_sdwan/datadog_checks/nn_sdwan/check.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/__init__.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/defaults.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/instance.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/shared.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/validators.py
  nn_sdwan/datadog_checks/nn_sdwan/data/conf.yaml.example
  nn_sdwan/datadog_checks/nn_sdwan/net_api.py
  nn_sdwan/images/netnology-logo.png
  nn_sdwan/manifest.json
  nn_sdwan/metadata.csv
  nn_sdwan/requirements-dev.txt
  nn_sdwan/requirements.in
  nn_sdwan/setup.py
  nn_sdwan/tests/__init__.py
  nn_sdwan/tests/conftest.py
  nn_sdwan/tests/metrics.py
  nn_sdwan/tests/test_nn_sdwan.py
  nn_sdwan/tox.ini
Labels: kind/new-integration, editorial review

#1323 DoControl integration with DDOG (for integration extras tile)
  .github/CODEOWNERS
  docontrol/CHANGELOG.md
  docontrol/README.md
  docontrol/assets/dashboards/docontrol_overview.json
  docontrol/assets/logos/DoControl_FullLogo_Black.svg
  docontrol/assets/logos/DoControl_FullLogo_Color.svg
  docontrol/assets/logos/DoControl_FullLogo_Color_White_RGB.svg
  docontrol/assets/logos/DoControl_FullLogo_White.svg
  docontrol/images/DC_DD_conf.png
  docontrol/images/DC_Secrets.png
  docontrol/images/DC_Utils.png
  docontrol/images/DC_WF_Create.png
  docontrol/images/Get_DD_API_Key.png
  docontrol/images/Get_DD_Application_Key.png
  docontrol/images/dc-dd-01.png
  docontrol/images/dc-dd-02.png
  docontrol/images/dc-dd-03.png
  docontrol/images/dc-dd-04.png
  docontrol/images/dc-dd-05.png
  docontrol/images/dc-dd-06.png
  docontrol/images/dc-dd-07.png
  docontrol/manifest.json
Labels: editorial review, kind/technology-partner

#1287 alertnow integration
  .github/CODEOWNERS
  alertnow/CHANGELOG.md
  alertnow/README.md
  alertnow/assets/dashboards/alertnow_overview.json
  alertnow/assets/service_checks.json
  alertnow/images/alertnow_overview.png
  alertnow/images/alertnow_tile_logo.png
  alertnow/images/create_integration_datadog_en.png
  alertnow/images/datadog_integration_detail.png
  alertnow/images/datadog_webhook.png
  alertnow/images/integration_card_datadog.png
  alertnow/manifest.json
  alertnow/metadata.csv
Labels: kind/new-integration, editorial review

#1339 Adds Backstage integration documentation
  .github/CODEOWNERS
  backstage/CHANGELOG.md
  backstage/README.md
  backstage/assets/dashboards/backstage_overview.json
  backstage/assets/service_checks.json
  backstage/images/.gitkeep
  backstage/manifest.json
  backstage/metadata.csv
Labels: editorial review

#1342 Komodor Integration Tile
  .github/CODEOWNERS
  komodor/CHANGELOG.md
  komodor/README.md
  komodor/assets/Komodor Terms of use.pdf
  komodor/images/Komodor_screen_01.png
  komodor/images/Komodor_screen_02.png
  komodor/images/Komodor_screen_03.png
  komodor/images/Komodor_screen_04.png
  komodor/images/Komodor_screen_05.png
  komodor/images/Komodor_screen_06.png
  komodor/images/Komodor_screen_07.png
  komodor/images/images.gitkeep
  komodor/manifest.json
  komodor/service_checks.json
Labels: editorial review, kind/technology-partner

#1346 Add the Gitea integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  gitea/CHANGELOG.md
  gitea/README.md
  gitea/assets/configuration/spec.yaml
  gitea/assets/dashboards/gitea_overview.json
  gitea/assets/service_checks.json
  gitea/datadog_checks/__init__.py
  gitea/datadog_checks/gitea/__about__.py
  gitea/datadog_checks/gitea/__init__.py
  gitea/datadog_checks/gitea/config_models/__init__.py
  gitea/datadog_checks/gitea/config_models/defaults.py
  gitea/datadog_checks/gitea/config_models/instance.py
  gitea/datadog_checks/gitea/config_models/shared.py
  gitea/datadog_checks/gitea/config_models/validators.py
  gitea/datadog_checks/gitea/data/auto_conf.yaml
  gitea/datadog_checks/gitea/data/conf.yaml.example
  gitea/datadog_checks/gitea/gitea.py
  gitea/datadog_checks/gitea/metrics.py
  gitea/images/.gitkeep
  gitea/images/gitea_logo.svg
  gitea/images/gitea_logo_text.svg
  gitea/manifest.json
  gitea/metadata.csv
  gitea/pyproject.toml
  gitea/requirements-dev.txt
  gitea/setup.py
  gitea/tests/__init__.py
  gitea/tests/conftest.py
  gitea/tests/docker/app.ini
  gitea/tests/docker/docker-compose.yaml
  gitea/tests/fixtures/metrics.txt
  gitea/tests/test_gitea.py
  gitea/tox.ini
Labels: editorial review
