Repository DataDog/integrations-extras, pull requests merged in 2022-01, with the labels that each got.

#1072 Use requests wrapper
  neutrona/datadog_checks/neutrona/neutrona.py
Labels: integration/neutrona

#1114 Superwise - Datadog Integration
  .github/CODEOWNERS
  superwise/CHANGELOG.md
  superwise/README.md
  superwise/assets/dashboards/superwise.json
  superwise/assets/service_checks.json
  superwise/images/.gitkeep
  superwise/images/2.png
  superwise/images/3.png
  superwise/images/4.png
  superwise/images/5.png
  superwise/images/6.png
  superwise/images/superwise-logo.png
  superwise/manifest.json
  superwise/metadata.csv
Labels: editorial review

#1119 [Documentation] Fix images
  superwise/images/3.png
  superwise/images/4.png
  superwise/images/5.png
  superwise/images/6.png
Labels: changelog/no-changelog

#1121 fix indent
  hbase_master/README.md
Labels: documentation, changelog/no-changelog, integration/hbase_master

#1096 add sedai
  .github/CODEOWNERS
  sedai/README.md
  sedai/assets/dashboards/sedai_overview.json
  sedai/assets/logo.svg
  sedai/assets/service_checks.json
  sedai/images/.gitkeep
  sedai/manifest.json
Labels: editorial review

#1095 Add a new TiDB Cloud Integration
  .github/CODEOWNERS
  tidb_cloud/README.md
  tidb_cloud/assets/dashboards/overview.json
  tidb_cloud/assets/service_checks.json
  tidb_cloud/images/logo.png
  tidb_cloud/manifest.json
  tidb_cloud/metadata.csv
Labels: editorial review

#1103 Add Twenty Forty Eight app
  .github/CODEOWNERS
  twenty_forty_eight/CHANGELOG.md
  twenty_forty_eight/README.md
  twenty_forty_eight/images/.gitkeep
  twenty_forty_eight/images/twenty-forty-eight.jpg
  twenty_forty_eight/manifest.json
Labels: kind/app

#1102 Add "The Data Runner" app
  .github/CODEOWNERS
  data_runner/CHANGELOG.md
  data_runner/README.md
  data_runner/images/.gitkeep
  data_runner/images/data-runner.jpg
  data_runner/manifest.json
Labels: editorial review, kind/app

#1116 removing AWS from Altostra manifest
  altostra/manifest.json
Labels: documentation, changelog/no-changelog, integration/altostra

#1126 [Documentation] Update docs with v2
  traefik/README.md
Labels: documentation, changelog/no-changelog
