Repository DataDog/integrations-extras, pull requests merged in 2022-10, with the labels that each got.

#1562 Add support for UMP and update dashboard
  unifi_console/README.md
  unifi_console/assets/configuration/spec.yaml
  unifi_console/assets/dashboards/unifi_console_overview.json
  unifi_console/datadog_checks/unifi_console/__about__.py
  unifi_console/datadog_checks/unifi_console/api.py
  unifi_console/datadog_checks/unifi_console/config.py
  unifi_console/datadog_checks/unifi_console/config_models/instance.py
  unifi_console/datadog_checks/unifi_console/data/conf.yaml.example
  unifi_console/datadog_checks/unifi_console/types.py
  unifi_console/tests/conftest.py
Labels: changelog/Fixed

#1535 Add Vantage Integration
  .github/CODEOWNERS
  vantage/CHANGELOG.md
  vantage/README.md
  vantage/assets/images/vantage-datadog-budget-forecast.png
  vantage/assets/images/vantage-datadog-grouped-report.png
  vantage/assets/images/vantage-datadog-provider-summary.png
  vantage/assets/logos/logo-dark.png
  vantage/assets/logos/logo-dark.svg
  vantage/assets/terms-of-service.pdf
  vantage/manifest.json
Labels: kind/technology-partner

#1552 Add Zenduty Integration
  .github/CODEOWNERS
  zenduty/CHANGELOG.md
  zenduty/README.md
  zenduty/assets/service_checks.json
  zenduty/images/alert_rules.png
  zenduty/images/incident_dashboard.png
  zenduty/images/incident_timeline.png
  zenduty/images/slack_controls.png
  zenduty/images/task_playbooks.png
  zenduty/manifest.json
  zenduty/metadata.csv
Labels: kind/technology-partner

#1511 Update README.md
  traefik/README.md
Labels: documentation, changelog/no-changelog, integration/traefik

#1520 (Docs) Add github action to check PRs for invalid partials
  .github/workflows/check_partials.py
  .github/workflows/check_partials.yml
Labels: documentation, changelog/no-changelog

#1582 OAuth configuration steps updated
  lambdatest/README.md
Labels: kind/technology-partner
