Repository DataDog/integrations-extras, pull requests merged in 2022-08, with the labels that each got.

#1285 Add support for IPv6 on Darwin
  ping/datadog_checks/ping/ping.py
  ping/tests/conftest.py
  ping/tests/test_ping.py
Labels: changelog/Added, integration/ping

#1384 Add curated metric column to n2ws metadata.csv
  n2ws/metadata.csv
Labels: changelog/Fixed

#1352 add Datazoom blog link
  datazoom/README.md
Labels: changelog/no-changelog

#1501 update events query example in readme
  configcat/README.md
Labels: changelog/no-changelog

#1311 Add cfssl integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  cfssl/CHANGELOG.md
  cfssl/README.md
  cfssl/assets/configuration/spec.yaml
  cfssl/assets/service_checks.json
  cfssl/datadog_checks/__init__.py
  cfssl/datadog_checks/cfssl/__about__.py
  cfssl/datadog_checks/cfssl/__init__.py
  cfssl/datadog_checks/cfssl/check.py
  cfssl/datadog_checks/cfssl/config_models/__init__.py
  cfssl/datadog_checks/cfssl/config_models/defaults.py
  cfssl/datadog_checks/cfssl/config_models/instance.py
  cfssl/datadog_checks/cfssl/config_models/shared.py
  cfssl/datadog_checks/cfssl/config_models/validators.py
  cfssl/datadog_checks/cfssl/data/conf.yaml.example
  cfssl/manifest.json
  cfssl/metadata.csv
  cfssl/pyproject.toml
  cfssl/requirements-dev.txt
  cfssl/setup.py
  cfssl/tests/__init__.py
  cfssl/tests/conftest.py
  cfssl/tests/docker-compose.yml
  cfssl/tests/test_cfssl.py
  cfssl/tox.ini
Labels: editorial review

#1326 Add integration for exim
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  exim/CHANGELOG.md
  exim/README.md
  exim/assets/configuration/spec.yaml
  exim/assets/dashboards/exim_overview.json
  exim/assets/service_checks.json
  exim/datadog_checks/__init__.py
  exim/datadog_checks/exim/__about__.py
  exim/datadog_checks/exim/__init__.py
  exim/datadog_checks/exim/check.py
  exim/datadog_checks/exim/config_models/__init__.py
  exim/datadog_checks/exim/config_models/defaults.py
  exim/datadog_checks/exim/config_models/instance.py
  exim/datadog_checks/exim/config_models/shared.py
  exim/datadog_checks/exim/config_models/validators.py
  exim/datadog_checks/exim/data/conf.yaml.example
  exim/images/.gitkeep
  exim/manifest.json
  exim/metadata.csv
  exim/pyproject.toml
  exim/requirements-dev.txt
  exim/setup.py
  exim/tests/__init__.py
  exim/tests/conftest.py
  exim/tests/fixtures/exiqsumm-empty.txt
  exim/tests/fixtures/exiqsumm.txt
  exim/tests/test_exim.py
  exim/tox.ini
Labels: kind/new-integration, editorial review

#1169 Add `pyproject.toml` file
  neutrona/MANIFEST.in
  neutrona/pyproject.toml
  neutrona/requirements.in
  neutrona/setup.py
  neutrona/tox.ini
Labels: changelog/Added, integration/neutrona

#1157 Add `pyproject.toml` file
  flume/MANIFEST.in
  flume/pyproject.toml
  flume/requirements.in
  flume/setup.py
  flume/tox.ini
Labels: changelog/Added, integration/flume

#1150 Add `pyproject.toml` file
  bind9/MANIFEST.in
  bind9/pyproject.toml
  bind9/requirements.in
  bind9/setup.py
  bind9/tox.ini
Labels: changelog/Added, integration/bind9

#1148 Add `pyproject.toml` file
  aqua/MANIFEST.in
  aqua/pyproject.toml
  aqua/requirements.in
  aqua/setup.py
  aqua/tox.ini
Labels: changelog/Added, integration/aqua

#1155 Add `pyproject.toml` file
  eventstore/MANIFEST.in
  eventstore/pyproject.toml
  eventstore/requirements.in
  eventstore/setup.py
  eventstore/tox.ini
Labels: changelog/Added, integration/eventstore

#1382 Insightfinder dashboard
  insightfinder/README.md
  insightfinder/assets/dashboards/ifdashboard.json
  insightfinder/manifest.json
Labels: kind/technology-partner

#1351 [New integration] unifi console
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  unifi_console/CHANGELOG.md
  unifi_console/Pipfile
  unifi_console/README.md
  unifi_console/assets/configuration/spec.yaml
  unifi_console/assets/dashboards/unifi_console_overview.json
  unifi_console/assets/service_checks.json
  unifi_console/datadog_checks/__init__.py
  unifi_console/datadog_checks/unifi_console/__about__.py
  unifi_console/datadog_checks/unifi_console/__init__.py
  unifi_console/datadog_checks/unifi_console/api.py
  unifi_console/datadog_checks/unifi_console/check.py
  unifi_console/datadog_checks/unifi_console/client_info.py
  unifi_console/datadog_checks/unifi_console/config.py
  unifi_console/datadog_checks/unifi_console/config_models/__init__.py
  unifi_console/datadog_checks/unifi_console/config_models/defaults.py
  unifi_console/datadog_checks/unifi_console/config_models/instance.py
  unifi_console/datadog_checks/unifi_console/config_models/shared.py
  unifi_console/datadog_checks/unifi_console/config_models/validators.py
  unifi_console/datadog_checks/unifi_console/data/conf.yaml.example
  unifi_console/datadog_checks/unifi_console/device_info.py
  unifi_console/datadog_checks/unifi_console/errors.py
  unifi_console/datadog_checks/unifi_console/mertrics.py
  unifi_console/datadog_checks/unifi_console/types.py
  unifi_console/images/.gitkeep
  unifi_console/manifest.json
  unifi_console/metadata.csv
  unifi_console/pyproject.toml
  unifi_console/requirements-dev.txt
  unifi_console/setup.py
  unifi_console/tests/__init__.py
  unifi_console/tests/common.py
  unifi_console/tests/conftest.py
  unifi_console/tests/fixtures/client_metrics.json
  unifi_console/tests/fixtures/client_metrics_values.json
  unifi_console/tests/fixtures/device_metrics.json
  unifi_console/tests/fixtures/device_metrics_values.json
  unifi_console/tests/fixtures/status_invalid.json
  unifi_console/tests/fixtures/status_valid.json
  unifi_console/tests/mocked_api.py
  unifi_console/tests/test_api.py
  unifi_console/tests/test_check.py
  unifi_console/tox.ini
Labels: kind/new-integration

#1519 zabbix: avoid sending non-numeric values as gauge
  zabbix/datadog_checks/zabbix/check.py
  zabbix/datadog_checks/zabbix/metrics.py
  zabbix/metadata.csv
Labels: changelog/Added

#1518 zabbix: Improve error handling when login
  zabbix/datadog_checks/zabbix/check.py
Labels: changelog/Added
