Repository DataDog/integrations-extras, pull requests merged in 2022-07, with the labels that each got.

#1327 Sosivio DataDog Integration
  .github/CODEOWNERS
  sosivio/CHANGELOG.md
  sosivio/README.md
  sosivio/assets/dashboards/sosivio_overview.json
  sosivio/assets/logos/avatars-bot.png
  sosivio/assets/logos/saas_logos-bot.png
  sosivio/assets/logos/saas_logos-small.png
  sosivio/assets/service_checks.json
  sosivio/images/datadog-sosivio-dashboard.png
  sosivio/manifest.json
  sosivio/metadata.csv
Labels: editorial review, kind/technology-partner

#1335 Firefly | Bring your cloud Up-to-Code
  .github/CODEOWNERS
  firefly/CHANGELOG.md
  firefly/README.md
  firefly/assets/logos/firefly-horizontal-logo.svg
  firefly/assets/logos/firefly-vertical-logo.svg
  firefly/assets/service_checks.json
  firefly/images/FF-codification.png
  firefly/images/FF-fix-drifts.png
  firefly/images/FF-insights.png
  firefly/images/FF-inventory.png
  firefly/manifest.json
Labels: editorial review, kind/technology-partner

#1364 docs: fix broken links in README files
  apache-apisix/README.md
  cert_manager/README.md
  gatekeeper/README.md
  neutrona/README.md
  nvml/README.md
  open_policy_agent/README.md
  rigor/README.md
  superwise/README.md
  zscaler/README.md
Labels: changelog/no-changelog, integration/rigor, integration/nvml, integration/gatekeeper, integration/open_policy_agent, integration/neutrona, integration/cert_manager, integration/apache-apisix, integration/superwise, integration/zscaler

#1367 Update config files
  cyral/datadog_checks/cyral/data/conf.yaml.example
  gatekeeper/datadog_checks/gatekeeper/data/auto_conf.yaml
  gatekeeper/datadog_checks/gatekeeper/data/conf.yaml.example
  jfrog_platform/datadog_checks/jfrog_platform/data/conf.yaml.example
  open_policy_agent/datadog_checks/open_policy_agent/data/auto_conf.yaml
  open_policy_agent/datadog_checks/open_policy_agent/data/conf.yaml.example
  pulsar/datadog_checks/pulsar/data/conf.yaml.example
  purefa/datadog_checks/purefa/data/conf.yaml.example
  purefb/datadog_checks/purefb/config_models/defaults.py
  purefb/datadog_checks/purefb/config_models/instance.py
  purefb/datadog_checks/purefb/data/conf.yaml.example
  redpanda/datadog_checks/redpanda/data/conf.yaml.example
  tidb/datadog_checks/tidb/data/conf.yaml.example
Labels: changelog/no-changelog, integration/cyral, integration/gatekeeper, integration/open_policy_agent, integration/tidb, integration/jfrog_platform, integration/pulsar, integration/redpanda, integration/purefa, integration/purefb

#1366 Remove Datadog licenses from config_models files
  fluentbit/datadog_checks/fluentbit/config_models/__init__.py
  fluentbit/datadog_checks/fluentbit/config_models/defaults.py
  fluentbit/datadog_checks/fluentbit/config_models/instance.py
  fluentbit/datadog_checks/fluentbit/config_models/shared.py
  gitea/datadog_checks/gitea/config_models/__init__.py
  gitea/datadog_checks/gitea/config_models/defaults.py
  gitea/datadog_checks/gitea/config_models/instance.py
  gitea/datadog_checks/gitea/config_models/shared.py
  neo4j/datadog_checks/neo4j/config_models/__init__.py
  neo4j/datadog_checks/neo4j/config_models/defaults.py
  neo4j/datadog_checks/neo4j/config_models/instance.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/__init__.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/defaults.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/instance.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/shared.py
  nn_sdwan/datadog_checks/nn_sdwan/config_models/validators.py
  purefa/datadog_checks/purefa/config_models/__init__.py
  purefa/datadog_checks/purefa/config_models/defaults.py
  purefa/datadog_checks/purefa/config_models/instance.py
  purefa/datadog_checks/purefa/config_models/shared.py
  purefb/datadog_checks/purefb/config_models/__init__.py
  purefb/datadog_checks/purefb/config_models/defaults.py
  purefb/datadog_checks/purefb/config_models/instance.py
  purefb/datadog_checks/purefb/config_models/shared.py
  syncthing/datadog_checks/syncthing/config_models/__init__.py
  syncthing/datadog_checks/syncthing/config_models/defaults.py
  syncthing/datadog_checks/syncthing/config_models/instance.py
  syncthing/datadog_checks/syncthing/config_models/shared.py
  trino/datadog_checks/trino/config_models/__init__.py
  trino/datadog_checks/trino/config_models/defaults.py
  trino/datadog_checks/trino/config_models/instance.py
  trino/datadog_checks/trino/config_models/shared.py
  trino/datadog_checks/trino/config_models/validators.py
Labels: changelog/no-changelog, integration/neo4j, integration/purefa, integration/fluentbit, integration/purefb, integration/gitea, integration/nn_sdwan, integration/trino, integration/syncthing

#1347 Add RUM integration for Android
  .github/CODEOWNERS
  rum_android/CHANGELOG.md
  rum_android/README.md
  rum_android/assets/service_checks.json
  rum_android/manifest.json
Labels: kind/new-integration, editorial review

#1357 Add RUM integration for iOS
  .github/CODEOWNERS
  rum_ios/CHANGELOG.md
  rum_ios/README.md
  rum_ios/assets/service_checks.json
  rum_ios/manifest.json
Labels: kind/new-integration, editorial review

#1363 Add RUM integration for Cypress
  .github/CODEOWNERS
  rum_cypress/CHANGELOG.md
  rum_cypress/README.md
  rum_cypress/assets/service_checks.json
  rum_cypress/manifest.json
Labels: editorial review

#1362 Add RUM integration for JavaScript
  .github/CODEOWNERS
  rum_javascript/CHANGELOG.md
  rum_javascript/README.md
  rum_javascript/assets/service_checks.json
  rum_javascript/manifest.json
Labels: editorial review

#1361 Add RUM integration for Angular
  .github/CODEOWNERS
  rum_angular/CHANGELOG.md
  rum_angular/README.md
  rum_angular/assets/service_checks.json
  rum_angular/manifest.json
Labels: editorial review

#1360 Add RUM integration for React
  .github/CODEOWNERS
  rum_react/CHANGELOG.md
  rum_react/README.md
  rum_react/assets/service_checks.json
  rum_react/manifest.json
Labels: editorial review
