Repository DataDog/integrations-extras, pull requests merged in 2022-11, with the labels that each got.

#1580 [nvml] add `compute_running_process` (processes running in gpu)
  nvml/CHANGELOG.md
  nvml/datadog_checks/nvml/__about__.py
  nvml/datadog_checks/nvml/data/conf.yaml.example
  nvml/datadog_checks/nvml/nvml.py
  nvml/metadata.csv
  nvml/tests/test_nvml.py
Labels: editorial review

#1600 Updating uninstallation instructions for Vantage
  vantage/README.md
Labels: kind/technology-partner

#1599 Updating uninstallation instructions for LambdaTest
  lambdatest/README.md
Labels: kind/technology-partner

#1601 grpc_check: Fix timeout default value
  grpc_check/CHANGELOG.md
  grpc_check/README.md
  grpc_check/datadog_checks/grpc_check/__about__.py
  grpc_check/datadog_checks/grpc_check/check.py
  grpc_check/datadog_checks/grpc_check/data/conf.yaml.example
  grpc_check/tests/test_grpc_check.py
Labels: changelog/Fixed

#1577 Add hikaricp integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  hikaricp/CHANGELOG.md
  hikaricp/README.md
  hikaricp/assets/configuration/spec.yaml
  hikaricp/assets/dashboards/hikaricp_overview.json
  hikaricp/assets/service_checks.json
  hikaricp/datadog_checks/__init__.py
  hikaricp/datadog_checks/hikaricp/__about__.py
  hikaricp/datadog_checks/hikaricp/__init__.py
  hikaricp/datadog_checks/hikaricp/check.py
  hikaricp/datadog_checks/hikaricp/config_models/__init__.py
  hikaricp/datadog_checks/hikaricp/config_models/defaults.py
  hikaricp/datadog_checks/hikaricp/config_models/instance.py
  hikaricp/datadog_checks/hikaricp/config_models/shared.py
  hikaricp/datadog_checks/hikaricp/config_models/validators.py
  hikaricp/datadog_checks/hikaricp/data/conf.yaml.example
  hikaricp/datadog_checks/hikaricp/metrics.py
  hikaricp/manifest.json
  hikaricp/metadata.csv
  hikaricp/pyproject.toml
  hikaricp/requirements-dev.txt
  hikaricp/setup.py
  hikaricp/tests/__init__.py
  hikaricp/tests/conftest.py
  hikaricp/tests/fixtures/metrics.txt
  hikaricp/tests/test_hikaricp.py
  hikaricp/tox.ini
Labels: editorial review

#1578 Adaptive Shield integration init
  .github/CODEOWNERS
  adaptive_shield/CHANGELOG.md
  adaptive_shield/README.md
  adaptive_shield/assets/adaptive_shield_logo_on_dark.svg
  adaptive_shield/assets/adaptive_shield_logo_on_light.svg
  adaptive_shield/assets/dashboards/adaptive_shield_overview.json
  adaptive_shield/assets/service_checks.json
  adaptive_shield/images/posture.png
  adaptive_shield/images/security_checks.png
  adaptive_shield/manifest.json
Labels: do-not-merge/HOLD, editorial review, kind/technology-partner

#1617 Remove dashboards that aren't registered in manifest
  alertnow/assets/dashboards/alertnow_overview.json
  backstage/assets/dashboards/backstage_overview.json
  cortex/assets/dashboards/cortex_overview.json
  docontrol/assets/dashboards/docontrol_overview.json
  exim/assets/dashboards/exim_overview.json
  fluentbit/assets/dashboards/fluent_bit_overview.json
  fluxcd/assets/dashboards/fluxcd_overview.json
  go_pprof_scraper/assets/dashboards/go_pprof_scraper_overview.json
  grpc_check/assets/dashboards/grpc_check_overview.json
  hikaricp/assets/dashboards/hikaricp_overview.json
  lightstep_incident_response/assets/dashboards/lightstep_incident_response_overview.json
  n2ws/assets/dashboards/N2WSBackup&Recovery-EntitiesSpecificDashboard.json
  n2ws/assets/dashboards/N2WSBackup&Recovery-Graphicalversion-areas.json
  n2ws/assets/dashboards/N2WSBackup&Recovery-Graphicalversion.json
  n2ws/assets/dashboards/N2WSBackup&RecoveryV4.0-BackupSuccessRates(ColumnGraphs).json
  n2ws/assets/dashboards/N2WSBackup&RecoveryV4.0-EntityTypesDetails.json
  unifi_console/assets/dashboards/unifi_console_overview.json
  zabbix/assets/dashboards/zabbix_overview.json
Labels: assets/no-dry-run

#1619 Update the paths to dashboards to be under the 'assets' folder
  launchdarkly/assets/dashboards/launchdarkly.json
  launchdarkly/manifest.json
  purefa/assets/dashboards/purefa_overview.json
  purefa/manifest.json
  purefb/assets/dashboards/purefb_overview.json
  purefb/manifest.json
Labels: assets/no-dry-run
