Repository DataDog/integrations-extras, pull requests merged in 2022-12, with the labels that each got.

#1561 update to Add F5 Cloud Services Integration
  .github/CODEOWNERS
  f5-distributed-cloud/CHANGELOG.md
  f5-distributed-cloud/README.md
  f5-distributed-cloud/assets/dashboards/f5xc_access.json
  f5-distributed-cloud/assets/logos/avatars-bot.png
  f5-distributed-cloud/assets/logos/f5xc.svg
  f5-distributed-cloud/assets/logos/saas_logos-bot.png
  f5-distributed-cloud/assets/logos/saas_logos-small.png
  f5-distributed-cloud/assets/saved_views/all.json
  f5-distributed-cloud/assets/service_checks.json
  f5-distributed-cloud/images/dashboard_image.png
  f5-distributed-cloud/images/image-0.png
  f5-distributed-cloud/images/logreceiver-config.png
  f5-distributed-cloud/manifest.json
Labels: editorial review, kind/technology-partner

#1587 Add NeoLoad integration
  .github/CODEOWNERS
  neoload/CHANGELOG.md
  neoload/README.md
  neoload/assets/dashboards/neoload_overview.json
  neoload/assets/logos/TricentisLogo.svg
  neoload/assets/service_checks.json
  neoload/images/neoload-dashboard.png
  neoload/manifest.json
  neoload/metadata.csv
Labels: editorial review, kind/technology-partner

#1597 Add Blink Integration
  .github/CODEOWNERS
  blink/CHANGELOG.md
  blink/README.md
  blink/assets/dashboards/blinkops_overview.json
  blink/assets/logos/Blink-dark.svg
  blink/assets/logos/Blink-light.svg
  blink/assets/service_checks.json
  blink/images/connection-creation.png
  blink/images/incident.png
  blink/images/list-incidents.png
  blink/images/new-incident.png
  blink/manifest.json
Labels: kind/technology-partner

#1543 Initial Commit, Drata created
  .github/CODEOWNERS
  drata/CHANGELOG.md
  drata/README.md
  drata/assets/logos/Drata Icon Black BG.svg
  drata/assets/logos/Drata Icon White Reversed.svg
  drata/assets/service_checks.json
  drata/images/.gitkeep
  drata/manifest.json
Labels: editorial review, kind/technology-partner

#1624 Update StormForge Optimize Live dashboard to new version
  stormforge/CHANGELOG.md
  stormforge/assets/dashboards/stormforge_overview.json
Labels: kind/technology-partner

#1608 Add filemage Integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  filemage/CHANGELOG.md
  filemage/README.md
  filemage/assets/configuration/spec.yaml
  filemage/assets/dashboards/overview.json
  filemage/assets/service_checks.json
  filemage/datadog_checks/__init__.py
  filemage/datadog_checks/filemage/__about__.py
  filemage/datadog_checks/filemage/__init__.py
  filemage/datadog_checks/filemage/check.py
  filemage/datadog_checks/filemage/common.py
  filemage/datadog_checks/filemage/config_models/__init__.py
  filemage/datadog_checks/filemage/config_models/defaults.py
  filemage/datadog_checks/filemage/config_models/instance.py
  filemage/datadog_checks/filemage/config_models/shared.py
  filemage/datadog_checks/filemage/config_models/validators.py
  filemage/datadog_checks/filemage/data/conf.yaml.example
  filemage/images/carousel-logo.jpg
  filemage/manifest.json
  filemage/metadata.csv
  filemage/pyproject.toml
  filemage/setup.py
  filemage/tests/__init__.py
  filemage/tests/common.py
  filemage/tests/conftest.py
  filemage/tests/test_filemage.py
  filemage/tox.ini
Labels: editorial review

#1568 Initial PR for Twingate integration
  .github/CODEOWNERS
  twingate/CHANGELOG.md
  twingate/README.md
  twingate/assets/configuration/spec.yaml
  twingate/assets/dashboards/twingate_overview.json
  twingate/images/Twingate Logo - Wide.png
  twingate/images/Twingate Logo – Icon.png
  twingate/images/dashboard.png
  twingate/images/twingate_activity_log.png
  twingate/manifest.json
Labels: kind/technology-partner

#1709 Typingdna activelock
  .github/CODEOWNERS
  typingdna_activelock/CHANGELOG.md
  typingdna_activelock/README.md
  typingdna_activelock/assets/dashboards/TypingDNAActiveLock.json
  typingdna_activelock/assets/logos/icon.png
  typingdna_activelock/assets/logos/typingdna-activelock.png
  typingdna_activelock/assets/logos/typingdna-activelock.svg
  typingdna_activelock/images/TypingDNAActiveLock.jpg
  typingdna_activelock/manifest.json
Labels: kind/technology-partner

#1703 go_pprof_scraper: properly encode UDS path in URL
  go_pprof_scraper/datadog_checks/go_pprof_scraper/check.py
  go_pprof_scraper/tests/conftest.py
Labels: changelog/Fixed
