Repository DataDog/integrations-extras, pull requests merged in 2023-10, with the labels that each got.

#2112 Update Uptycs event source and query filter in dashboard
  uptycs/assets/dashboards/uptycs.json
  uptycs/manifest.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2127 change Uptycs events dashboard source filter to lower case
  uptycs/assets/dashboards/uptycs.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#1887 Add protocol for puma datadog control_url integration
  puma/CHANGELOG.md
  puma/assets/configuration/spec.yaml
  puma/datadog_checks/puma/__about__.py
  puma/datadog_checks/puma/data/conf.yaml.example
Labels: agent/review-requested, docs/review-requested, product/review-requested, ecosystems/review-requested

#2129 Update outdated URLs for steadybit
  steadybit/README.md
  steadybit/assets/dashboards/steadybit.json
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2144 update to dashboard
  singlestoredb_cloud/CHANGELOG.md
  singlestoredb_cloud/assets/dashboards/singlestoredb_cloud_overview.json
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2118 YugabyteDB Managed Integration
  .github/CODEOWNERS
  yugabytedb_managed/CHANGELOG.md
  yugabytedb_managed/README.md
  yugabytedb_managed/assets/dashboards/yugabytedb_managed_overview.json
  yugabytedb_managed/assets/logos/yugabytedb_managed_logo.svg
  yugabytedb_managed/assets/logos/yugabytedb_managed_logo_dark.svg
  yugabytedb_managed/assets/service_checks.json
  yugabytedb_managed/images/infrastructure.png
  yugabytedb_managed/images/master.png
  yugabytedb_managed/images/overview.png
  yugabytedb_managed/images/tserver.png
  yugabytedb_managed/images/ycql.png
  yugabytedb_managed/images/ysql.png
  yugabytedb_managed/manifest.json
  yugabytedb_managed/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/requested-changes, product/logos-complete, ecosystems/approved
