Repository DataDog/integrations-extras, pull requests merged in 2023-11, with the labels that each got.

#2155 Create Tailscale Overview Dashboard
  tailscale/assets/dashboards/tailscale_overview.json
  tailscale/manifest.json
Labels: editorial review

#2165 Fixing link in Notion docs
  notion/README.md
Labels: kind/technology-partner, docs/approved, product/review-requested, ecosystems/approved

#2158 NS1 Integration: TTL dashboard fix
  ns1/assets/dashboards/overview.json
Labels: kind/bug, kind/technology-partner, product/approved, ecosystems/approved

#2146 Change query for top 10 zones usage to match top 10 records
  ns1/assets/dashboards/overview.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2108 Updated ilert integration readme, added and modified images
  ilert/README.md
  ilert/images/datadog-alert-source-new-2.png
  ilert/images/datadog-alert-source-new-3.png
  ilert/images/datadog-alert-source-new.png
  ilert/images/datadog-alert-source-view.png
  ilert/images/ilert-alert-list.png
  ilert/manifest.json
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2124 changelog/Added Invary Runtime Integrity initial integration metadata
  .github/CODEOWNERS
  invary/CHANGELOG.md
  invary/README.md
  invary/assets/dashboards/invary_runtime_integrity.json
  invary/assets/logos/invary.svg
  invary/assets/service_checks.json
  invary/images/dashboard.png
  invary/manifest.json
Labels: editorial review, kind/technology-partner, hold/log-pipelines, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2162 PureFB Version 1.0.4 - add new metric purefb.nfs.export_rule
  purefb/CHANGELOG.md
  purefb/README.md
  purefb/datadog_checks/purefb/__about__.py
  purefb/datadog_checks/purefb/data/conf.yaml.example
  purefb/datadog_checks/purefb/metrics.py
  purefb/metadata.csv
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/approved

#2122 Add Robust Intelligence AI Firewall integration tile
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  robust_intelligence_ai_firewall/CHANGELOG.md
  robust_intelligence_ai_firewall/README.md
  robust_intelligence_ai_firewall/assets/configuration/spec.yaml
  robust_intelligence_ai_firewall/assets/dashboards/robust_intelligence_ai_firewall_overview.json
  robust_intelligence_ai_firewall/assets/logos/RI_Black_Vertical.svg
  robust_intelligence_ai_firewall/assets/logos/RI_White_Vertical.svg
  robust_intelligence_ai_firewall/assets/service_checks.json
  robust_intelligence_ai_firewall/datadog_checks/__init__.py
  robust_intelligence_ai_firewall/datadog_checks/robust_intelligence_ai_firewall/__about__.py
  robust_intelligence_ai_firewall/datadog_checks/robust_intelligence_ai_firewall/__init__.py
  robust_intelligence_ai_firewall/datadog_checks/robust_intelligence_ai_firewall/data/conf.yaml.example
  robust_intelligence_ai_firewall/datadog_checks/robust_intelligence_ai_firewall/firewall_check.py
  robust_intelligence_ai_firewall/datadog_checks/robust_intelligence_ai_firewall/metrics.py
  robust_intelligence_ai_firewall/hatch.toml
  robust_intelligence_ai_firewall/images/ai-firewall.png
  robust_intelligence_ai_firewall/images/firewall-dashboard.png
  robust_intelligence_ai_firewall/images/ri-dashboard-banner.png
  robust_intelligence_ai_firewall/manifest.json
  robust_intelligence_ai_firewall/metadata.csv
  robust_intelligence_ai_firewall/pyproject.toml
  robust_intelligence_ai_firewall/setup.py
  robust_intelligence_ai_firewall/tests/__init__.py
  robust_intelligence_ai_firewall/tests/conftest.py
  robust_intelligence_ai_firewall/tests/fixtures/firewall_metrics.txt
  robust_intelligence_ai_firewall/tests/test_robust_intelligence_ai_firewall.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2160 Update NVML API version for compatibility with latest pynvml.
  nvml/CHANGELOG.md
  nvml/datadog_checks/nvml/__about__.py
  nvml/datadog_checks/nvml/nvml.py
  nvml/pyproject.toml
  nvml/requirements.in
  nvml/tests/Dockerfile
  nvml/tests/test_nvml.py
Labels: integration/nvml

#2170 Update CloudZero integration content and branding
  cloudzero/README.md
  cloudzero/assets/logos/cloudzero-logostacked-color.svg
  cloudzero/assets/logos/cloudzero-logostacked-inverted.svg
  cloudzero/images/CloudZero1.png
  cloudzero/images/CloudZero2.png
  cloudzero/images/cloudZero-logo.svg
  cloudzero/manifest.json
Labels: product/approved, product/logos-complete

#2120 JFrog Platform Cloud
  .github/CODEOWNERS
  jfrog_platform_cloud/CHANGELOG.md
  jfrog_platform_cloud/README.md
  jfrog_platform_cloud/assets/dashboards/jfrog_platform_cloud_overview.json
  jfrog_platform_cloud/assets/images/ART.png
  jfrog_platform_cloud/assets/images/jfrog-platform-cloud.png
  jfrog_platform_cloud/assets/service_checks.json
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_0.png
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_1.png
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_2.png
  jfrog_platform_cloud/manifest.json
Labels: kind/technology-partner, hold/log-pipelines, agent/approved, docs/approved, product/approved, ecosystems/synced, ecosystems/approved

#2138 added Upstash Integration
  .github/CODEOWNERS
  upstash/CHANGELOG.md
  upstash/README.md
  upstash/assets/dashboards/upstash_overview.json
  upstash/assets/service_checks.json
  upstash/images/logo-dark.svg
  upstash/images/logo-light.svg
  upstash/images/upstash-dashboard.png
  upstash/manifest.json
  upstash/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/synced, ecosystems/approved, ecosystems/oauth-synced

#2184 bump min base package version
  purefa/CHANGELOG.md
  purefa/pyproject.toml
Labels: changelog/Fixed
