Repository DataDog/integrations-extras, pull requests merged in 2023-04, with the labels that each got.

#1790 Fix typo in iOS integration
  rum_ios/README.md
Labels: documentation, changelog/no-changelog

#1767 Add integration tile for Mendix
  .github/CODEOWNERS
  mendix/CHANGELOG.md
  mendix/README.md
  mendix/assets/dashboards/MendixApplicationOverview.json
  mendix/assets/logos/mendix_dark.svg
  mendix/assets/logos/mendix_light.svg
  mendix/assets/service_checks.json
  mendix/images/cloud_resource_pack_overview.png
  mendix/images/cp_deployment_app_running.png
  mendix/images/domain-model-with-data-hub.png
  mendix/images/mendix_dashboard.png
  mendix/images/page-editor.png
  mendix/manifest.json
  mendix/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/requested-changes

#1811 Config for ruff linter
  .flake8
  pyproject.toml
Labels: changelog/no-changelog

#1741 Add Instabug Integration
  .github/CODEOWNERS
  instabug/CHANGELOG.md
  instabug/README.md
  instabug/assets/service_checks.json
  instabug/images/Instabug-Logo.svg
  instabug/images/instabug-app-overview.png
  instabug/images/instabug-bugs.png
  instabug/images/instabug-crash-details.png
  instabug/images/instabug-crashes-list.png
  instabug/images/instabug-datadog-widget.png
  instabug/images/instabug-releases-page.png
  instabug/manifest.json
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, marketplace/approved

#1782 feat: add mergify integration
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  mergify/CHANGELOG.md
  mergify/README.md
  mergify/assets/configuration/spec.yaml
  mergify/assets/dashboards/mergify_overview.json
  mergify/assets/service_checks.json
  mergify/datadog_checks/__init__.py
  mergify/datadog_checks/mergify/__about__.py
  mergify/datadog_checks/mergify/__init__.py
  mergify/datadog_checks/mergify/check.py
  mergify/datadog_checks/mergify/config_models/__init__.py
  mergify/datadog_checks/mergify/config_models/defaults.py
  mergify/datadog_checks/mergify/config_models/instance.py
  mergify/datadog_checks/mergify/config_models/shared.py
  mergify/datadog_checks/mergify/config_models/validators.py
  mergify/datadog_checks/mergify/data/conf.yaml.example
  mergify/hatch.toml
  mergify/images/IMAGES_README.md
  mergify/manifest.json
  mergify/metadata.csv
  mergify/pyproject.toml
  mergify/tests/__init__.py
  mergify/tests/conftest.py
  mergify/tests/fixtures/queues.json
  mergify/tests/test_mergify.py
Labels: editorial review

#1818 Removing "Integration" from titles
  1e/manifest.json
  bottomline_recordandreplay/manifest.json
  signl4/manifest.json
Labels: docs/approved, marketplace/synced, marketplace/approved

#1816 Update dashboard for Mendix tile
  mendix/CHANGELOG.md
  mendix/assets/dashboards/MendixApplicationOverview.json
  mendix/images/cp_deployment_app_running.png
  mendix/manifest.json
Labels: kind/technology-partner, marketplace/approved

#1793 Added Flagsmith datadog widget
  flagsmith/README.md
Labels: kind/technology-partner, marketplace/approved

#1817 Blink Datadog actions docs 404
  blink/README.md
Labels: kind/technology-partner, docs/review-requested

#1576 Cybersixgill Actionable Alerts
  .azure-pipelines/all.yml
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  cybersixgill_actionable_alerts/CHANGELOG.md
  cybersixgill_actionable_alerts/README.md
  cybersixgill_actionable_alerts/assets/configuration/spec.yaml
  cybersixgill_actionable_alerts/assets/dashboards/cybersixgill_actionable_alerts_overview.json
  cybersixgill_actionable_alerts/assets/service_checks.json
  cybersixgill_actionable_alerts/datadog_checks/__init__.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/__about__.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/__init__.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/check.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/config_models/__init__.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/config_models/defaults.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/config_models/instance.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/config_models/shared.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/config_models/validators.py
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/data/conf.yaml.example
  cybersixgill_actionable_alerts/datadog_checks/cybersixgill_actionable_alerts/date_threshold.txt
  cybersixgill_actionable_alerts/hatch.toml
  cybersixgill_actionable_alerts/images/cybersixgill_logo_svg.svg
  cybersixgill_actionable_alerts/images/dashboard_count.PNG
  cybersixgill_actionable_alerts/images/dashboard_emerging_alerts_count.PNG
  cybersixgill_actionable_alerts/images/dashboard_events_list.PNG
  cybersixgill_actionable_alerts/images/dashboard_imminent_alerts_count.PNG
  cybersixgill_actionable_alerts/images/transparent.png
  cybersixgill_actionable_alerts/manifest.json
  cybersixgill_actionable_alerts/metadata.csv
  cybersixgill_actionable_alerts/pyproject.toml
  cybersixgill_actionable_alerts/requirements.txt
  cybersixgill_actionable_alerts/setup.py
  cybersixgill_actionable_alerts/tests/__init__.py
  cybersixgill_actionable_alerts/tests/conftest.py
  cybersixgill_actionable_alerts/tests/test_cybersixgill_actionable_alerts.py
  cybersixgill_actionable_alerts/tests/test_instance.py
  cybersixgill_actionable_alerts/tests/test_shared.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, marketplace/synced, marketplace/approved

#1800 Update README file for F5 Distributed cloud integration
  f5-distributed-cloud/README.md
  f5-distributed-cloud/assets/saved_views/all.json
Labels: kind/technology-partner
