Repository DataDog/integrations-extras, pull requests merged in 2023-01, with the labels that each got.

#1715 unifi Refactor the api for better support of new api and additional device types
  unifi_console/CHANGELOG.md
  unifi_console/README.md
  unifi_console/datadog_checks/unifi_console/UAP.py
  unifi_console/datadog_checks/unifi_console/UDM.py
  unifi_console/datadog_checks/unifi_console/USG.py
  unifi_console/datadog_checks/unifi_console/USW.py
  unifi_console/datadog_checks/unifi_console/USX.py
  unifi_console/datadog_checks/unifi_console/__about__.py
  unifi_console/datadog_checks/unifi_console/api.py
  unifi_console/datadog_checks/unifi_console/check.py
  unifi_console/datadog_checks/unifi_console/client.py
  unifi_console/datadog_checks/unifi_console/client_info.py
  unifi_console/datadog_checks/unifi_console/common.py
  unifi_console/datadog_checks/unifi_console/config.py
  unifi_console/datadog_checks/unifi_console/device.py
  unifi_console/datadog_checks/unifi_console/device_info.py
  unifi_console/datadog_checks/unifi_console/errors.py
  unifi_console/datadog_checks/unifi_console/mertrics.py
  unifi_console/datadog_checks/unifi_console/types.py
  unifi_console/datadog_checks/unifi_console/unifi.py
  unifi_console/hatch.toml
  unifi_console/tests/conftest.py
  unifi_console/tests/fixtures/client_metrics_values.json
  unifi_console/tests/fixtures/device_metrics_values.json
  unifi_console/tests/mocked_api.py
  unifi_console/tests/test_api.py
  unifi_console/tests/test_check.py
  unifi_console/tests/test_unifi.py
Labels: changelog/Changed

#1693 Add Buoyant Cloud integration
  .github/CODEOWNERS
  buoyant_cloud/CHANGELOG.md
  buoyant_cloud/README.md
  buoyant_cloud/assets/dashboards/buoyant_cloud_overview.json
  buoyant_cloud/assets/logos/buoyant_cloud.svg
  buoyant_cloud/assets/service_checks.json
  buoyant_cloud/images/bcloud_01.png
  buoyant_cloud/images/bcloud_02.png
  buoyant_cloud/images/bcloud_03.png
  buoyant_cloud/images/bcloud_04.png
  buoyant_cloud/images/bcloud_05.png
  buoyant_cloud/images/bcloud_06.png
  buoyant_cloud/images/bcloud_07.png
  buoyant_cloud/images/bcloud_datadog_dashboard.png
  buoyant_cloud/manifest.json
  buoyant_cloud/metadata.csv
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, product/logos-complete, marketplace/synced, marketplace/approved, marketplace/oauth-synced, marketplace/oauth-staging-synced

#1719 Update README.md
  twingate/README.md
Labels: kind/technology-partner, docs/approved, product/approved, marketplace/synced

#1724 update api keys link to filter to app title
  adaptive_shield/README.md
  buoyant_cloud/README.md
  lambdatest/README.md
  vantage/README.md
Labels: kind/technology-partner, docs/approved, product/approved, marketplace/synced, marketplace/approved

#1725 (DOCS-4595) Add event details
  buoyant_cloud/README.md
Labels: kind/technology-partner, product/approved, marketplace/synced, marketplace/approved

#1623 Update PureFB - 1.0.2
  purefb/CHANGELOG.md
  purefb/README.md
  purefb/datadog_checks/purefb/__about__.py
  purefb/datadog_checks/purefb/metrics.py
  purefb/metadata.csv
Labels: kind/technology-partner

#1728 modifying the dashboard and changing the Datadog Agent to tag the log…
  twingate/README.md
  twingate/assets/dashboards/twingate_overview.json
Labels: kind/technology-partner

#1731 Update TypingDNAActiveLock.json
  typingdna_activelock/assets/dashboards/TypingDNAActiveLock.json
Labels: kind/technology-partner, product/approved, marketplace/synced, marketplace/approved

#1695 Add Steadybit integration
  .github/CODEOWNERS
  steadybit/CHANGELOG.md
  steadybit/README.md
  steadybit/assets/dashboards/steadybit.json
  steadybit/assets/logos/steadybit_logo.svg
  steadybit/assets/service_checks.json
  steadybit/images/steadybit_events_in_datadog.png
  steadybit/images/steadybit_experiment_editor.png
  steadybit/images/steadybit_experiment_execution_monitor_status_over_time.png
  steadybit/images/steadybit_experiment_execution_run_log.png
  steadybit/manifest.json
  steadybit/metadata.csv
Labels: editorial review, kind/technology-partner, product/approved, product/logos-complete, marketplace/synced, marketplace/approved
