Repository DataDog/integrations-extras, pull requests merged in 2023-03, with the labels that each got.

#1777 DOCS-4971 Batch Cleanup Deprecated Classifier Tag
  adaptive_shield/manifest.json
  agora_analytics/manifest.json
  alertnow/manifest.json
  apptrail/manifest.json
  data_runner/manifest.json
  docontrol/manifest.json
  embrace_mobile/manifest.json
  eversql/manifest.json
  f5-distributed-cloud/manifest.json
  fairwinds_insights_ui/manifest.json
  fiddler/manifest.json
  finout/manifest.json
  firefly/manifest.json
  harness_cloud_cost_management/manifest.json
  komodor/manifest.json
  launchdarkly/manifest.json
  pagerduty/manifest.json
  purefa/manifest.json
  purefb/manifest.json
  rookout/manifest.json
  twenty_forty_eight/manifest.json
  vantage/manifest.json
  zebrium/manifest.json
Labels: agent/approved, docs/approved, marketplace/approved

#1766 Add IsDown Integration
  .github/CODEOWNERS
  isdown/CHANGELOG.md
  isdown/README.md
  isdown/assets/dashboards/isdown_overview.json
  isdown/assets/logos/logo.svg
  isdown/assets/service_checks.json
  isdown/images/isdown_dashboards.jpg
  isdown/images/isdown_datadog_dashboard.jpg
  isdown/images/isdown_datadog_flow.jpg
  isdown/manifest.json
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, marketplace/approved

#1794 DOCS-5095 Rename "OS System" to "OS & System"
  filebeat/manifest.json
  kernelcare/manifest.json
  nvml/manifest.json
  purefa/manifest.json
  purefb/manifest.json
  reboot_required/manifest.json
  redis_sentinel/manifest.json
  upsc/manifest.json
  uptime/manifest.json
Labels: marketplace/synced, marketplace/approved

#1778 Add Blink oauth
  .github/CODEOWNERS
  blink/README.md
  blink/images/incident.png
  blink/manifest.json
Labels: kind/technology-partner, product/approved, marketplace/oauth-synced, marketplace/oauth-staging-synced

#1779 Add Ably integration
  .github/CODEOWNERS
  ably/CHANGELOG.md
  ably/README.md
  ably/assets/dashboards/ably.json
  ably/assets/logos/ably-badge-round.svg
  ably/assets/logos/ably.svg
  ably/assets/logos/avatars-bot.png
  ably/assets/logos/saas_logos-bot.png
  ably/assets/logos/saas_logos-small.png
  ably/assets/service_checks.json
  ably/images/ably-dashboard.png
  ably/images/integrations.png
  ably/images/setup-integration.png
  ably/images/uninstall-integration.png
  ably/images/your-apps.png
  ably/manifest.json
  ably/metadata.csv
Labels: editorial review, kind/technology-partner, product/requested-changes, marketplace/synced, marketplace/approved, marketplace/oauth-synced, marketplace/oauth-staging-synced

#1791 Update README.md
  convox/README.md
Labels: documentation, changelog/no-changelog, integration/convox
