Repository DataDog/integrations-extras, pull requests merged in 2023-08, with the labels that each got.

#1889 Updated the ./assets/logos to match split.io rebrand done in May 2023.
  .github/CODEOWNERS
  split-rum/CHANGELOG.md
  split-rum/README.md
  split-rum/images/split-feature-flag-detail-in-dd-rum.png
  split-rum/images/split-feature-flags-list-in-dd-rum.png
  split-rum/manifest.json
  split/assets/logos/avatars-bot.png
  split/assets/logos/saas_logos-bot.png
  split/assets/logos/saas_logos-small.png
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/requested-changes

#1890 Added hikaricp.connections.max (pool max size)
  hikaricp/datadog_checks/hikaricp/metrics.py
  hikaricp/metadata.csv
  hikaricp/tests/test_hikaricp.py
Labels: changelog/Added, integration/hikaricp

#2070 [Release] Bumped hikaricp version to 1.1.0
  hikaricp/CHANGELOG.md
  hikaricp/datadog_checks/hikaricp/__about__.py
Labels: mergequeue-status: error

#2047 Adds cloudzero integration
  .github/CODEOWNERS
  cloudzero/CHANGELOG.md
  cloudzero/README.md
  cloudzero/images/CloudZero1.png
  cloudzero/images/CloudZero2.png
  cloudzero/images/cloudZero-logo.svg
  cloudzero/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/requested-changes, product/approved, product/logos-complete, ecosystems/synced, ecosystems/oauth-synced, ecosystems/review-requested

#2072 Fix changelog formatting
  split-rum/CHANGELOG.md
Labels: docs/review-requested, product/review-requested, ecosystems/review-requested

#2074 Migrate recommended monitor runs to new pipeline
  .github/workflows/validate.yml
Labels: agent/approved, product/review-requested, ecosystems/review-requested

#2080 update lacework doc
  lacework/README.md
Labels: docs/review-requested, product/review-requested, ecosystems/review-requested

#2081 add mongo db overview dashboard
  mongodb_atlas/assets/dashboards/MongoDB-Atlas-Overview_dashboard.json
  mongodb_atlas/manifest.json
Labels: product/review-requested, ecosystems/review-requested

#2076 Adding new AI and ML categories to integrations
  algorithmia/manifest.json
  federatorai/manifest.json
  fiddler/datadog_checks/fiddler/config_models/defaults.py
  fiddler/datadog_checks/fiddler/config_models/instance.py
  fiddler/datadog_checks/fiddler/config_models/shared.py
  fiddler/manifest.json
  insightfinder/manifest.json
  logzio/manifest.json
  nvml/manifest.json
  stormforge/manifest.json
  superwise/manifest.json
Labels: agent/approved, docs/approved, product/review-requested, ecosystems/approved

#2078 NVML: Upgrade grpcio dep to address linux/arm64 build error
  nvml/CHANGELOG.md
  nvml/datadog_checks/nvml/__about__.py
  nvml/pyproject.toml
  nvml/requirements.in
  nvml/tests/Dockerfile
Labels: agent/approved, docs/review-requested, product/review-requested, ecosystems/review-requested

#2086 Add AI classifier tag
  nvml/manifest.json
Labels: agent/approved, product/review-requested, ecosystems/review-requested
