Repository DataDog/integrations-extras, pull requests merged in 2024-09, with the labels that each got.

#2481 [MA-5658] Migrate monitor name in manifest to be aligned with monitor asset title
  algorithmia/manifest.json
  bottomline_recordandreplay/manifest.json
  emnify/manifest.json
  federatorai/manifest.json
  mongodb_atlas/manifest.json
  nn_sdwan/manifest.json
  nomad/manifest.json
  php_apcu/manifest.json
  php_opcache/manifest.json
  seagence/manifest.json
  sigsci/manifest.json
  syncthing/manifest.json
  tailscale/manifest.json
  upbound_uxp/manifest.json
  zenoh_router/manifest.json
Labels: mergequeue-status: rejected

#2484 [LOGSC-1852] Fix test file for Fauna integration
  fauna/assets/logs/fauna_tests.yaml
Labels: kind/technology-partner, product/review-requested, ecosystems/approved

#2480 [Buoyant Cloud] Replace mem.sum with mem.max
  buoyant_cloud/CHANGELOG.md
  buoyant_cloud/assets/dashboards/buoyant_cloud_overview.json
  buoyant_cloud/metadata.csv
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2434 Upstash Redis Dashboard Rework
  upstash/CHANGELOG.md
  upstash/assets/dashboards/upstash_kafka_overview.json
  upstash/assets/dashboards/upstash_overview.json
  upstash/assets/dashboards/upstash_redis_overview.json
  upstash/images/upstash-redis-overview-dashboard.png
  upstash/manifest.json
  upstash/metadata.csv
Labels: kind/technology-partner, docs/review-requested, product/HOLD, product/approved, ecosystems/approved

#2426 [Onepane] Adds Onepane Integration (ECOINT-3)
  .github/CODEOWNERS
  onepane/CHANGELOG.md
  onepane/README.md
  onepane/assets/dashboards/onepane_overview.json
  onepane/assets/logos/onepane_dark.svg
  onepane/assets/logos/onepane_light.svg
  onepane/assets/oauth_clients.json
  onepane/assets/service_checks.json
  onepane/images/confirmation.png
  onepane/images/dashboard.png
  onepane/images/deploying.png
  onepane/images/integration.png
  onepane/images/onepane_prompt.png
  onepane/images/uninstall.png
  onepane/manifest.json
  onepane/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2477 docs: add kameleoon rum integration (ECOINT-10)
  .github/CODEOWNERS
  kameleoon/CHANGELOG.md
  kameleoon/README.md
  kameleoon/assets/logos/Kameleoon.svg
  kameleoon/images/rum_dashboard.png
  kameleoon/images/rum_details.png
  kameleoon/manifest.json
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-requested, ecosystems/approved

#2490 Quick PR: made fauna onboarding url secure
  fauna/assets/oauth_clients.json
Labels: mergequeue-status: removed

#2356 Gigamon (ECOINT-9)
  .github/CODEOWNERS
  gigamon/CHANGELOG.md
  gigamon/README.md
  gigamon/assets/dashboards/gigamon_overview.json
  gigamon/assets/logs/gigamon.yaml
  gigamon/assets/logs/gigamon_tests.yaml
  gigamon/assets/service_checks.json
  gigamon/images/final logo.svg
  gigamon/images/gd1.png
  gigamon/images/gd2.png
  gigamon/images/gd3.png
  gigamon/images/gigamon1.png
  gigamon/images/gigamon2.png
  gigamon/images/gigamondashboard.png
  gigamon/manifest.json
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, ecosystems/approved, assets/deploy-logs-staging

#2383 Redis cloud (ECOINT-5)
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  redis_cloud/CHANGELOG.md
  redis_cloud/README.md
  redis_cloud/assets/configuration/spec.yaml
  redis_cloud/assets/dashboards/redis_cloud_database.json
  redis_cloud/assets/dashboards/redis_cloud_networking.json
  redis_cloud/assets/dashboards/redis_cloud_overview.json
  redis_cloud/assets/logos/logo.svg
  redis_cloud/assets/service_checks.json
  redis_cloud/datadog_checks/__init__.py
  redis_cloud/datadog_checks/redis_cloud/__about__.py
  redis_cloud/datadog_checks/redis_cloud/__init__.py
  redis_cloud/datadog_checks/redis_cloud/check.py
  redis_cloud/datadog_checks/redis_cloud/config_models/__init__.py
  redis_cloud/datadog_checks/redis_cloud/config_models/defaults.py
  redis_cloud/datadog_checks/redis_cloud/config_models/instance.py
  redis_cloud/datadog_checks/redis_cloud/config_models/shared.py
  redis_cloud/datadog_checks/redis_cloud/config_models/validators.py
  redis_cloud/datadog_checks/redis_cloud/data/conf.yaml.example
  redis_cloud/datadog_checks/redis_cloud/data/redis_cloud.yaml
  redis_cloud/datadog_checks/redis_cloud/metrics.py
  redis_cloud/hatch.toml
  redis_cloud/images/datadog-cloud-cluster-database.png
  redis_cloud/images/datadog-cloud-node-dashboard.png
  redis_cloud/images/datadog-cloud-overview-dashboard.png
  redis_cloud/manifest.json
  redis_cloud/metadata.csv
  redis_cloud/pyproject.toml
  redis_cloud/tests/__init__.py
  redis_cloud/tests/conftest.py
  redis_cloud/tests/data/metrics.txt
  redis_cloud/tests/support.py
  redis_cloud/tests/test_redis_cloud.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved
