Repository DataDog/integrations-extras, pull requests merged in 2024-02, with the labels that each got.

#2277 adaptive_shield - images - posture and security_checks
  adaptive_shield/images/posture.png
  adaptive_shield/images/security_checks.png
Labels: kind/technology-partner, product/review-requested, ecosystems/approved

#2280 DOCS-7136 Integrations Doc Update
  cockroachdb_dedicated/metadata.csv
Labels: documentation, changelog/no-changelog

#2256 Adding Keep
  .github/CODEOWNERS
  keep/CHANGELOG.md
  keep/README.md
  keep/images/alert-rules.png
  keep/images/alerts-page.png
  keep/images/integrations-page.png
  keep/images/keep-logo.svg
  keep/images/workflow-builder.png
  keep/images/workflows.png
  keep/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved, assets/no-deploy

#2287 Fix upload/download bandwidth metrics
  speedtest/assets/dashboards/speedtest.json
  speedtest/datadog_checks/speedtest/__init__.py
  speedtest/datadog_checks/speedtest/check.py
  speedtest/datadog_checks/speedtest/speedtest.py
  speedtest/metadata.csv
  speedtest/tests/test_speedtest.py
Labels: changelog/Fixed, integration/speedtest

#2269 Fix NS1 queries for top 10 zones & TTL and remove legacy DDI product
  ns1/assets/dashboards/overview.json
  ns1/datadog_checks/ns1/check.py
  ns1/datadog_checks/ns1/data/conf.yaml.example
  ns1/datadog_checks/ns1/ns1_api_url.py
  ns1/datadog_checks/ns1/ns1_url_utils.py
  ns1/metadata.csv
  ns1/tests/conftest.py
  ns1/tests/test_ns1.py
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2299 Remove Linux from SupportedOS Classifier tags
  jamf_protect/manifest.json
Labels: mergequeue-status: error

#2293 JFrog, update dashboard
  jfrog_platform_cloud/README.md
  jfrog_platform_cloud/assets/dashboards/jfrog_platform_cloud_overview.json
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2254 Add Zenoh router integration
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  zenoh_router/CHANGELOG.md
  zenoh_router/README.md
  zenoh_router/assets/configuration/spec.yaml
  zenoh_router/assets/dashboards/zenoh_routers_overview.json
  zenoh_router/assets/monitors/zenoh_router_disconnected.json
  zenoh_router/assets/service_checks.json
  zenoh_router/datadog_checks/__init__.py
  zenoh_router/datadog_checks/zenoh_router/__about__.py
  zenoh_router/datadog_checks/zenoh_router/__init__.py
  zenoh_router/datadog_checks/zenoh_router/check.py
  zenoh_router/datadog_checks/zenoh_router/config_models/__init__.py
  zenoh_router/datadog_checks/zenoh_router/config_models/defaults.py
  zenoh_router/datadog_checks/zenoh_router/config_models/instance.py
  zenoh_router/datadog_checks/zenoh_router/config_models/shared.py
  zenoh_router/datadog_checks/zenoh_router/config_models/validators.py
  zenoh_router/datadog_checks/zenoh_router/data/conf.yaml.example
  zenoh_router/hatch.toml
  zenoh_router/manifest.json
  zenoh_router/metadata.csv
  zenoh_router/pyproject.toml
  zenoh_router/setup.py
  zenoh_router/tests/__init__.py
  zenoh_router/tests/conftest.py
  zenoh_router/tests/test_unit.py
Labels: editorial review, assets/no-deploy

#2135 Create Modal integration tile
  .github/CODEOWNERS
  modal/CHANGELOG.md
  modal/README.md
  modal/assets/dashboards/modal.json
  modal/assets/service_checks.json
  modal/images/modal-banner.png
  modal/images/modal-datadog-dashboard.jpg
  modal/images/modal-logo-datadog.png
  modal/images/modal-product-hero.jpg
  modal/images/modal.jpg
  modal/manifest.json
  modal/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-requested, ecosystems/approved

#2302 [hbase_master] Update hbase_master metrics.yaml to be Agent 6/7 compatible by default
  hbase_master/CHANGELOG.md
  hbase_master/datadog_checks/hbase_master/__about__.py
  hbase_master/datadog_checks/hbase_master/data/metrics.yaml
Labels: kind/bug, changelog/Fixed
