Repository DataDog/integrations-extras, pull requests merged in 2024-03, with the labels that each got.

#2175 EMQX Agent Integration
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  emqx/CHANGELOG.md
  emqx/README.md
  emqx/assets/configuration/spec.yaml
  emqx/assets/dashboards/overview.json
  emqx/assets/logos/avatars-bot.png
  emqx/assets/logos/emqx-with-watermark.svg
  emqx/assets/logos/emqx.svg
  emqx/assets/logos/saas_logos-bot.png
  emqx/assets/logos/saas_logos-small.png
  emqx/assets/service_checks.json
  emqx/datadog_checks/__init__.py
  emqx/datadog_checks/emqx/__about__.py
  emqx/datadog_checks/emqx/__init__.py
  emqx/datadog_checks/emqx/check.py
  emqx/datadog_checks/emqx/config_models/__init__.py
  emqx/datadog_checks/emqx/config_models/defaults.py
  emqx/datadog_checks/emqx/config_models/instance.py
  emqx/datadog_checks/emqx/config_models/shared.py
  emqx/datadog_checks/emqx/config_models/validators.py
  emqx/datadog_checks/emqx/data/conf.yaml.example
  emqx/datadog_checks/emqx/metrics.py
  emqx/hatch.toml
  emqx/images/emqx-overview-1.png
  emqx/images/emqx-overview-2.png
  emqx/images/emqx-overview-3.png
  emqx/images/emqx-overview-4.png
  emqx/images/emqx-overview-5.png
  emqx/manifest.json
  emqx/metadata.csv
  emqx/pyproject.toml
  emqx/setup.py
  emqx/tests/__init__.py
  emqx/tests/conftest.py
  emqx/tests/fixtures/metrics.txt
  emqx/tests/test_emqx.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2215 Add Vercel metrics metadata
  vercel/manifest.json
  vercel/metadata.csv
Labels: assets/no-deploy

#2250 (DOCS-6993) Remove duplicated content
  split/README.md
Labels: mergequeue-status: error, assets/no-deploy

#2284 LoadRunner Professional Integration Tile
  .github/CODEOWNERS
  loadrunner_professional/CHANGELOG.md
  loadrunner_professional/README.md
  loadrunner_professional/assets/dashboards/loadrunner_professional_overview.json
  loadrunner_professional/assets/logos/loadrunner_logo.png
  loadrunner_professional/assets/logos/loadrunner_logo_4x3.png
  loadrunner_professional/assets/logos/loadrunner_logo_small.png
  loadrunner_professional/assets/logs/loadrunner_professional.yaml
  loadrunner_professional/assets/logs/loadrunner_professional_tests.yaml
  loadrunner_professional/assets/service_checks.json
  loadrunner_professional/images/analysis_summary.png
  loadrunner_professional/images/controller_design.png
  loadrunner_professional/images/controller_run.png
  loadrunner_professional/images/datadog_configuration_window.png
  loadrunner_professional/images/vugen_new.png
  loadrunner_professional/manifest.json
  loadrunner_professional/metadata.csv
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-requested, ecosystems/approved, assets/deploy-logs-staging

#2308 Upstash Kafka metrics and dashboards added
  upstash/CHANGELOG.md
  upstash/assets/dashboards/upstash_kafka_overview.json
  upstash/images/upstash-kafka-overview-dashboard.png
  upstash/manifest.json
  upstash/metadata.csv
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2317 fix: low emqx's datadog-checks-base to 32.6.0
  emqx/CHANGELOG.md
  emqx/README.md
  emqx/pyproject.toml
Labels: kind/technology-partner, agent/review-requested, docs/approved, product/approved, ecosystems/approved

#2330 [LoadRunner] fix banner image link
  loadrunner_professional/assets/dashboards/loadrunner_professional_overview.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2328 metric query adjusted on Upstash Kafka Overview Dashboard
  upstash/assets/dashboards/upstash_kafka_overview.json
Labels: kind/technology-partner, product/approved, ecosystems/approved
