Repository DataDog/integrations-extras, pull requests merged in 2024-04, with the labels that each got.

#2314 Fix db_name taggin on Neo4j v4
  neo4j/CHANGELOG.md
  neo4j/datadog_checks/neo4j/__about__.py
  neo4j/datadog_checks/neo4j/neo4j.py
  neo4j/hatch.toml
  neo4j/tests/docker/docker-compose_v4.yaml
  neo4j/tests/docker/docker-compose_v5.yaml
  neo4j/tests/docker/neo4j4/docker-compose.yaml
  neo4j/tests/docker/neo4j5/docker-compose.yaml
Labels: changelog/Fixed, integration/neo4j

#2334 Explanatory tile for how to integrate with Discord using webhooks
  .github/CODEOWNERS
  discord/CHANGELOG.md
  discord/README.md
  discord/assets/icon_clyde_blurple_RGB.png
  discord/manifest.json
Labels: editorial review

#2338 added moovingon.ai tile
  .github/CODEOWNERS
  moovingon_ai/CHANGELOG.md
  moovingon_ai/README.md
  moovingon_ai/assets/dashboards/moovingon.ai_overview.json
  moovingon_ai/assets/logos/moovingon-ai.svg
  moovingon_ai/assets/logos/moovingon.ai_blue.svg
  moovingon_ai/assets/logos/moovingon.ai_white.svg
  moovingon_ai/assets/oauth_clients.json
  moovingon_ai/assets/service_checks.json
  moovingon_ai/images/moovingon.ai-integrations.png
  moovingon_ai/images/moovingon_ai-events.png
  moovingon_ai/images/moovingon_ai-guidelines.png
  moovingon_ai/images/moovingon_ai-overview-dashbard.png
  moovingon_ai/manifest.json
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2310 patch : metric mapping for DI and Performance metrics, to support backwards compatibility from v23.7+
  fiddler/CHANGELOG.md
  fiddler/README.md
  fiddler/datadog_checks/fiddler/__about__.py
  fiddler/datadog_checks/fiddler/check.py
  fiddler/metadata.csv
  fiddler/tests/test_fiddler.py
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/approved

#2357 Update auth0.yaml to add new data.types
  auth0/assets/logs/auth0.yaml
Labels: assets/deploy-logs-staging

#2340 Updated Neo4j Integration to add metrics introduced into Neo4j since 5.10
  neo4j/CHANGELOG.md
  neo4j/assets/configuration/spec.yaml
  neo4j/datadog_checks/__init__.py
  neo4j/datadog_checks/neo4j/__init__.py
  neo4j/datadog_checks/neo4j/config_models/defaults.py
  neo4j/datadog_checks/neo4j/data/conf.yaml.example
  neo4j/datadog_checks/neo4j/metrics.py
  neo4j/metadata.csv
  neo4j/setup.py
  neo4j/tests/common.py
  neo4j/tests/conftest.py
  neo4j/tests/test_neo4j.py
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2351 JFrog Cloud integration, update the dashboard and screenshots and add…
  jfrog_platform_cloud/assets/dashboards/jfrog_platform_cloud_overview.json
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_0.png
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_1.png
  jfrog_platform_cloud/images/jfrog_platform_cloud_logs_2.png
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, ecosystems/approved
