Repository DataDog/integrations-extras, pull requests merged in 2024-11, with the labels that each got.

#2528 Hide old Mergify page
  mergify/manifest.json
Labels: kind/technology-partner, docs/approved, product/review-requested, ecosystems/approved

#2513 Artie integration (ECOINT-13)
  .github/CODEOWNERS
  artie/CHANGELOG.md
  artie/README.md
  artie/assets/dashboards/artie_overview.json
  artie/assets/logos/logo_dark_mode.svg
  artie/assets/logos/logo_light_mode.svg
  artie/assets/oauth_clients.json
  artie/assets/service_checks.json
  artie/images/artie-overview-dashboard.png
  artie/manifest.json
  artie/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2347 Added Anecdote Integration (ECOINT-2)
  .github/CODEOWNERS
  anecdote/CHANGELOG.md
  anecdote/README.md
  anecdote/assets/dashboards/anecdote_bug_reports.json
  anecdote/assets/logos/Anecdote Logo SVG.svg
  anecdote/assets/logs/anecdote.yaml
  anecdote/assets/logs/anecdote_tests.yaml
  anecdote/assets/oauth_clients.json
  anecdote/assets/service_checks.json
  anecdote/images/1.png
  anecdote/images/2.png
  anecdote/images/3.png
  anecdote/images/4.png
  anecdote/manifest.json
  anecdote/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved, assets/deploy-logs-staging

#2386 CloudAEye Integration with Datadog (ECOINT-19)
  .github/CODEOWNERS
  cloudaeye/CHANGELOG.md
  cloudaeye/README.md
  cloudaeye/assets/dashboards/CloudAEye_overview.json
  cloudaeye/assets/logos/logo-dark.png
  cloudaeye/assets/logos/logo-dark.svg
  cloudaeye/assets/service_checks.json
  cloudaeye/images/assistant.png
  cloudaeye/images/cloudAEyeKosalDashboard.png
  cloudaeye/images/global-context.png
  cloudaeye/images/notifications.png
  cloudaeye/images/root-cause-analysis.png
  cloudaeye/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2540 Update oauth_clients.json with new redirect uri and permission list
  doctordroid/assets/oauth_clients.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2548 Add missing permissions in GitHub Actions workflows.
  .github/workflows/master.yml
  .github/workflows/publish-test-results-pr.yml
Labels: changelog/no-changelog
