Repository DataDog/integrations-extras, pull requests merged in 2024-07, with the labels that each got.

#2417 Redis enterprise - added dash to name of overview dashboard
  .codecov.yml
  redis_enterprise/assets/dashboards/redis_enterprise_overview.json
  redis_enterprise/datadog_checks/redis_enterprise/check.py
  redis_enterprise/datadog_checks/redis_enterprise/data/conf.yaml.example
  redis_enterprise/manifest.json
  redis_enterprise/metadata.csv
  redis_enterprise/tests/test_redis_enterprise.py
  redisenterprise/README.md
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2432 Add IP ranges note
  rundeck/README.md
Labels: changelog/no-changelog, mergequeue-status: rejected

#2427 Add/Remove/Update metric names for PureFB v2.0.0
  purefb/CHANGELOG.md
  purefb/README.md
  purefb/assets/dashboards/purefb_overview.json
  purefb/datadog_checks/purefb/__about__.py
  purefb/datadog_checks/purefb/config_models/instance.py
  purefb/datadog_checks/purefb/data/conf.yaml.example
  purefb/datadog_checks/purefb/metrics.py
  purefb/metadata.csv
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/approved

#2441 Update Ably dashboard logo
  ably/assets/dashboards/ably.json
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2437 update scopes for cloudzero integration
  cloudzero/CHANGELOG.md
  cloudzero/assets/oauth_clients.json
  cloudzero/manifest.json
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2442 PureFB v2.0.1 - rename incorrectly named metric
  purefb/CHANGELOG.md
  purefb/assets/dashboards/purefb_overview.json
  purefb/datadog_checks/purefb/metrics.py
  purefb/metadata.csv
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/approved

#2436 JFrog Self-hosted integration, fix logs and metrics dashboards.
  jfrog_platform_self_hosted/assets/dashboards/jfrog_artifactory_logs_(self-hosted).json
  jfrog_platform_self_hosted/assets/dashboards/jfrog_artifactory_metrics_(self-hosted).json
  jfrog_platform_self_hosted/datadog_checks/jfrog_platform_self_hosted/data/conf.yaml.example
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2433 Redis enterprise
  redis_enterprise/README.md
  redis_enterprise/assets/configuration/spec.yaml
  redis_enterprise/assets/dashboards/redis_enterprise_database.json
  redis_enterprise/assets/dashboards/redis_enterprise_overview.json
  redis_enterprise/datadog_checks/redis_enterprise/check.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/defaults.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/instance.py
  redis_enterprise/datadog_checks/redis_enterprise/data/conf.yaml.example
  redis_enterprise/manifest.json
  redis_enterprise/metadata.csv
  redis_enterprise/tests/test_redis_enterprise.py
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2407 Add Webb.ai integration tile
  .github/CODEOWNERS
  webb_ai/CHANGELOG.md
  webb_ai/README.md
  webb_ai/assets/dashboards/webb_ai_overview.json
  webb_ai/assets/logos/logo-light.png
  webb_ai/assets/logos/logo-light.svg
  webb_ai/assets/oauth_clients.json
  webb_ai/images/webb_ai-datadog-dashboard.jpg
  webb_ai/images/webb_ai-rca-summary.jpg
  webb_ai/images/webb_ai-troubleshooting-steps.jpg
  webb_ai/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2425 Add Fauna integration
  .github/CODEOWNERS
  fauna/CHANGELOG.md
  fauna/README.md
  fauna/assets/dashboards/fauna_overview.json
  fauna/assets/logos/Fauna-logo-color.svg
  fauna/assets/logs/fauna.yaml
  fauna/assets/logs/fauna_tests.yaml
  fauna/assets/oauth_clients.json
  fauna/assets/service_checks.json
  fauna/images/fauna_dashboard_2.png
  fauna/images/fauna_dashboard_logs.png
  fauna/images/fauna_dashboard_overview.png
  fauna/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved, assets/deploy-logs-staging
