Repository DataDog/integrations-extras, pull requests merged in 2024-10, with the labels that each got.

#2456 Add a new OceanBase Cloud Integration (ECOINT-7)
  .github/CODEOWNERS
  oceanbasecloud/CHANGELOG.md
  oceanbasecloud/README.md
  oceanbasecloud/assets/dashboards/oceanbasecloud_overview.json
  oceanbasecloud/assets/oauth_clients.json
  oceanbasecloud/assets/service_checks.json
  oceanbasecloud/images/logo.svg
  oceanbasecloud/images/ob-dashboard.jpg
  oceanbasecloud/images/ob-host.jpg
  oceanbasecloud/images/ob-sql.jpg
  oceanbasecloud/images/ob-transaction.jpg
  oceanbasecloud/manifest.json
  oceanbasecloud/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2501 [Doc] Update Link to CelerData Metrics
  celerdata/README.md
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved, mergequeue-status: rejected

#2457 DDS: F5 Distributed Cloud integration (V2.0.0)
  f5-distributed-cloud/CHANGELOG.md
  f5-distributed-cloud/README.md
  f5-distributed-cloud/assets/dashboards/f5xc_bot_defense_events_overview.json
  f5-distributed-cloud/assets/dashboards/f5xc_waf_events_overview.json
  f5-distributed-cloud/assets/logos/F5DCS_logo.svg
  f5-distributed-cloud/assets/logs/f5-distributed-cloud-services.yaml
  f5-distributed-cloud/assets/logs/f5-distributed-cloud-services_tests.yaml
  f5-distributed-cloud/images/F5DCS-BOT-Defense-Events-Overview.png
  f5-distributed-cloud/images/F5DCS-WAF-Events-Overview.png
  f5-distributed-cloud/manifest.json
Labels: assets/deploy-logs-staging

#2460 Add Doppler integration (ECOINT-6)
  .github/CODEOWNERS
  doppler/CHANGELOG.md
  doppler/README.md
  doppler/assets/configuration/spec.yaml
  doppler/assets/dashboards/doppler_overview.json
  doppler/assets/logs/doppler.yaml
  doppler/assets/logs/doppler_tests.yaml
  doppler/assets/oauth_clients.json
  doppler/assets/service_checks.json
  doppler/images/dashboard.png
  doppler/images/doppler-logo.svg
  doppler/images/example-log.png
  doppler/images/generate.png
  doppler/images/personal-config.png
  doppler/images/projects.png
  doppler/images/rotation.png
  doppler/images/secret-visibility.png
  doppler/images/version-history.png
  doppler/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved, assets/deploy-logs-staging

#2515 Update Modal uninstallation instructions
  modal/README.md
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2497 renamed replication, added shard and proxy-threads
  redis_enterprise/CHANGELOG.md
  redis_enterprise/README.md
  redis_enterprise/assets/configuration/spec.yaml
  redis_enterprise/assets/dashboards/redis_enterprise_active-active.json
  redis_enterprise/assets/dashboards/redis_enterprise_proxy-threads.json
  redis_enterprise/assets/dashboards/redis_enterprise_proxy.json
  redis_enterprise/assets/dashboards/redis_enterprise_shard.json
  redis_enterprise/datadog_checks/redis_enterprise/__about__.py
  redis_enterprise/datadog_checks/redis_enterprise/data/conf.yaml.example
  redis_enterprise/datadog_checks/redis_enterprise/metrics.py
  redis_enterprise/manifest.json
  redis_enterprise/metadata.csv
  redis_enterprise/tests/support.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2487 Prepare for Mergify built-in integration (ECOINT-20)
  .github/CODEOWNERS
  mergify/README.md
  mergify/manifest.json
  mergify_oauth/CHANGELOG.md
  mergify_oauth/README.md
  mergify_oauth/assets/dashboards/mergify_overview.json
  mergify_oauth/assets/logos/mergify-logo.svg
  mergify_oauth/assets/oauth_clients.json
  mergify_oauth/assets/service_checks.json
  mergify_oauth/images/dashboard.png
  mergify_oauth/manifest.json
  mergify_oauth/metadata.csv
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-requested, ecosystems/review-requested

#2478 Specifying supported Metrics for Embrace integration
  embrace_mobile/manifest.json
  embrace_mobile/metadata.csv
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2493 feat: Add CloudQuery Cloud integration (ECOINT-35)
  .github/CODEOWNERS
  cloudquery-cloud/CHANGELOG.md
  cloudquery-cloud/README.md
  cloudquery-cloud/assets/oauth_clients.json
  cloudquery-cloud/images/cloudquery_logo_png_dark_background.png
  cloudquery-cloud/images/cloudquery_logo_png_light_background.png
  cloudquery-cloud/images/cloudquery_logo_svg_dark_background.svg
  cloudquery-cloud/images/cloudquery_logo_svg_light_background.svg
  cloudquery-cloud/manifest.json
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2502 [Doc] Update An Image Link for OceanBase Cloud
  oceanbasecloud/CHANGELOG.md
  oceanbasecloud/assets/dashboards/oceanbasecloud_overview.json
  oceanbasecloud/assets/oauth_clients.json
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2518 Adding scaphandre integration
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  scaphandre/CHANGELOG.md
  scaphandre/README.md
  scaphandre/assets/configuration/spec.yaml
  scaphandre/assets/dashboards/scaphandre_overview.json
  scaphandre/assets/service_checks.json
  scaphandre/datadog_checks/__init__.py
  scaphandre/datadog_checks/scaphandre/__about__.py
  scaphandre/datadog_checks/scaphandre/__init__.py
  scaphandre/datadog_checks/scaphandre/check.py
  scaphandre/datadog_checks/scaphandre/config_models/__init__.py
  scaphandre/datadog_checks/scaphandre/config_models/defaults.py
  scaphandre/datadog_checks/scaphandre/config_models/instance.py
  scaphandre/datadog_checks/scaphandre/config_models/shared.py
  scaphandre/datadog_checks/scaphandre/config_models/validators.py
  scaphandre/datadog_checks/scaphandre/data/conf.yaml.example
  scaphandre/datadog_checks/scaphandre/metrics.py
  scaphandre/hatch.toml
  scaphandre/manifest.json
  scaphandre/metadata.csv
  scaphandre/pyproject.toml
  scaphandre/tests/__init__.py
  scaphandre/tests/common.py
  scaphandre/tests/conftest.py
  scaphandre/tests/docker/Caddyfile
  scaphandre/tests/docker/docker_compose.yaml
  scaphandre/tests/fixtures/output.txt
  scaphandre/tests/test_e2e.py
  scaphandre/tests/test_unit.py
Labels: editorial review

#2508 Update Agora Analytics dashboard to add widgets for chat metrics
  agora_analytics/CHANGELOG.md
  agora_analytics/README.md
  agora_analytics/assets/dashboards/agora_analytics_overview.json
  agora_analytics/images/agora_analytics_dashboard.png
  agora_analytics/metadata.csv
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved
