Repository DataDog/integrations-extras, pull requests merged in 2024-05, with the labels that each got.

#2322 Cockcroach cloud integration update
  cockroachdb_dedicated/CHANGELOG.md
  cockroachdb_dedicated/README.md
  cockroachdb_dedicated/assets/dashboards/cockroach_cloud_dedicated_overview.json
  cockroachdb_dedicated/assets/dashboards/cockroach_cloud_serverless_overview.json
  cockroachdb_dedicated/manifest.json
  cockroachdb_dedicated/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2369 moovingon.ai | Missing events_read scope
  moovingon_ai/README.md
  moovingon_ai/assets/oauth_clients.json
  moovingon_ai/images/moovingon_ai-events.png
  moovingon_ai/manifest.json
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2312 Redis enterprise
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  .gitignore
  redis_enterprise/CHANGELOG.md
  redis_enterprise/README.md
  redis_enterprise/assets/configuration/spec.yaml
  redis_enterprise/assets/dashboards/redis_enterprise_database.json
  redis_enterprise/assets/dashboards/redis_enterprise_node.json
  redis_enterprise/assets/dashboards/redis_enterprise_overview.json
  redis_enterprise/assets/logos/logo.svg
  redis_enterprise/assets/service_checks.json
  redis_enterprise/datadog_checks/__init__.py
  redis_enterprise/datadog_checks/redis_enterprise/__about__.py
  redis_enterprise/datadog_checks/redis_enterprise/__init__.py
  redis_enterprise/datadog_checks/redis_enterprise/check.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/__init__.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/defaults.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/instance.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/shared.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/validators.py
  redis_enterprise/datadog_checks/redis_enterprise/data/conf.yaml.example
  redis_enterprise/datadog_checks/redis_enterprise/metrics.py
  redis_enterprise/hatch.toml
  redis_enterprise/images/datadog-detail-node-cpu.png
  redis_enterprise/images/datadog-detail-node-memory.png
  redis_enterprise/images/datadog-detail-requests.png
  redis_enterprise/manifest.json
  redis_enterprise/metadata.csv
  redis_enterprise/pyproject.toml
  redis_enterprise/tests/__init__.py
  redis_enterprise/tests/conftest.py
  redis_enterprise/tests/data/metrics.txt
  redis_enterprise/tests/support.py
  redis_enterprise/tests/test_redis_enterprise.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2346 Add Eppo integration tile
  .github/CODEOWNERS
  eppo/CHANGELOG.md
  eppo/README.md
  eppo/assets/dashboards/eppo_dashboard.json
  eppo/assets/logos/eppo-black.svg
  eppo/assets/service_checks.json
  eppo/images/eppo_datadog1.png
  eppo/images/eppo_datadog2.png
  eppo/images/eppo_datadog3.png
  eppo/manifest.json
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2365 PerfectScale integration
  .github/CODEOWNERS
  perfectscale/CHANGELOG.md
  perfectscale/README.md
  perfectscale/assets/dashboards/perfectscale_alerts.json
  perfectscale/assets/logos/perfectscale-logo-color.svg
  perfectscale/assets/service_checks.json
  perfectscale/images/perfectscale-alerts.png
  perfectscale/images/perfectscale-anomalies.png
  perfectscale/images/perfectscale-connect-cluster.png
  perfectscale/images/perfectscale-dashboard.png
  perfectscale/images/perfectscale-datadog-dashboard.png
  perfectscale/manifest.json
Labels: editorial review, kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2326 [Celerdata] integration with CelerData
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  celerdata/CHANGELOG.md
  celerdata/README.md
  celerdata/assets/configuration/spec.yaml
  celerdata/assets/dashboards/CelerData.json
  celerdata/assets/logos/celerdata-logo.svg
  celerdata/assets/logs/celerdata.yaml
  celerdata/assets/logs/celerdata_tests.yaml
  celerdata/assets/service_checks.json
  celerdata/datadog_checks/__init__.py
  celerdata/datadog_checks/celerdata/__about__.py
  celerdata/datadog_checks/celerdata/__init__.py
  celerdata/datadog_checks/celerdata/celerdata.py
  celerdata/datadog_checks/celerdata/config_models/__init__.py
  celerdata/datadog_checks/celerdata/config_models/defaults.py
  celerdata/datadog_checks/celerdata/config_models/instance.py
  celerdata/datadog_checks/celerdata/config_models/shared.py
  celerdata/datadog_checks/celerdata/config_models/validators.py
  celerdata/datadog_checks/celerdata/data/conf.yaml.example
  celerdata/datadog_checks/celerdata/metrics.py
  celerdata/hatch.toml
  celerdata/images/celerdata-dashboard.png
  celerdata/images/celerdata-logs.png
  celerdata/manifest.json
  celerdata/metadata.csv
  celerdata/pyproject.toml
  celerdata/tests/__init__.py
  celerdata/tests/common.py
  celerdata/tests/conftest.py
  celerdata/tests/docker/docker-compose.yaml
  celerdata/tests/test_celerdata.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-requested, product/logos-complete, ecosystems/approved, assets/deploy-logs-staging

#2385 Bryce/update rundeck image
  rundeck/README.md
  rundeck/images/search-dd-2024.png
Labels: changelog/no-changelog, mergequeue-status: error

#2399 (DOCS-7761) Update screenshots for nav
  split-rum/images/split-feature-flag-detail-in-dd-rum.png
  split-rum/images/split-feature-flags-list-in-dd-rum.png
  torq/README.md
  torq/images/datadog_api_key_2.png
  torq/images/datadog_app_key_2.png
  torq/images/datadog_webhook_config.png
  torq/images/datadog_webhook_search.png
Labels: changelog/no-changelog

#2380 Redis Enterprise: Minor README Edits
  redis_enterprise/README.md
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved
