Repository DataDog/integrations-extras, pull requests merged in 2024-01, with the labels that each got.

#2207 Add the Tailscale blog post to its public doc
  tailscale/README.md
Labels: changelog/no-changelog

#2239 JFrog update dashboard
  jfrog_platform_cloud/assets/dashboards/jfrog_platform_cloud_overview.json
Labels: kind/technology-partner, product/approved, ecosystems/review-requested

#2203 Upstash Dashboard's default values adjusted
  upstash/assets/dashboards/upstash_overview.json
  upstash/images/upstash-dashboard.png
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2266 [ECOS 1144] reduce jfrog image file size to pass image validations
  jfrog_platform_self_hosted/images/jfrog_xray_violations.png
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2237 Add Doctor Droid
  .github/CODEOWNERS
  doctordroid/CHANGELOG.md
  doctordroid/README.md
  doctordroid/assets/dashboards/doctor_droid_overview.json
  doctordroid/assets/logos/Horizontal_Logo.svg
  doctordroid/assets/logos/Icon.svg
  doctordroid/assets/service_checks.json
  doctordroid/assets/terms-of-service.pdf
  doctordroid/images/alert_occurence_count_trends.png
  doctordroid/images/doctor_droid_overview.png
  doctordroid/images/top_10_lifetime_alert_counts.png
  doctordroid/images/top_5_alerts_distribution.png
  doctordroid/manifest.json
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/synced, ecosystems/approved, ecosystems/oauth-synced, ecosystems/oauth-staging-synced

#2232 Replace v1 aggregated_metrics API with faster v2 queries API in Fiddler Agent
  fiddler/CHANGELOG.md
  fiddler/README.md
  fiddler/datadog_checks/fiddler/__about__.py
  fiddler/datadog_checks/fiddler/check.py
  fiddler/hatch.toml
  fiddler/metadata.csv
  fiddler/pyproject.toml
  fiddler/tests/conftest.py
  fiddler/tests/test_fiddler.py
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/approved

#2275 JFrog update dashboard
  jfrog_platform_cloud/assets/dashboards/jfrog_platform_cloud_overview.json
Labels: kind/technology-partner, product/review-requested, ecosystems/approved, assets/no-deploy
