Repository DataDog/integrations-extras, pull requests merged in 2025-07, with the labels that each got.

#2719 [ECOINT-212] Redpanda v2.1.0 - Support for lag metrics
  redpanda/CHANGELOG.md
  redpanda/README.md
  redpanda/assets/dashboards/consumers.json
  redpanda/assets/dashboards/overview.json
  redpanda/datadog_checks/redpanda/__about__.py
  redpanda/datadog_checks/redpanda/data/conf.yaml.example
  redpanda/datadog_checks/redpanda/metrics.py
  redpanda/hatch.toml
  redpanda/manifest.json
  redpanda/metadata.csv
  redpanda/tests/common.py
  redpanda/tests/docker/docker-compose.yaml
  redpanda/tests/fixtures/redpanda_metrics.txt
  redpanda/tests/test_redpanda.py
Labels: kind/technology-partner, agent/approved, docs/review-requested, product/approved, ecosystems/review-requested

#2730 Update mocked data on instabug blueprint asset
  instabug/assets/app-builder-blueprints/instabug-sessions-explorer.json
Labels: assets/no-dry-run

#2698 Fix typo in redisenterprise README.md
  redisenterprise/README.md
Labels: changelog/no-changelog
