Repository DataDog/integrations-extras, pull requests merged in 2025-08, with the labels that each got.

#2751 [ECOINT-253] [TiDB Metrics Integration] Create a New Dashboard for TiDB Monitoring
  tidb/datadog_checks/tidb/data/conf.yaml.example
  tidb/manifest.json
  tidb_cloud/CHANGELOG.md
  tidb_cloud/assets/dashboards/overview-metrics-integration.json
  tidb_cloud/manifest.json
Labels: kind/technology-partner, docs/review-requested, product/approved, ecosystems/approved

#2760 [ECOINT-263] Update README.md
  k6/README.md
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2761 [ECOINT-264] Refactor extract_billing to include records data
  ns1/CHANGELOG.md
  ns1/README.md
  ns1/datadog_checks/ns1/__about__.py
  ns1/datadog_checks/ns1/check.py
  ns1/tests/test_ns1.py
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved

#2776 Mendix troubleshooting note
  mendix/README.md
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved, mergequeue-status: rejected
