Repository DataDog/integrations-extras, pull requests merged in 2025-03, with the labels that each got.

#2580 Reflectiz integration release (ECOINT-23)
  .github/CODEOWNERS
  reflectiz/Changelog.md
  reflectiz/README.md
  reflectiz/assets/dashboards/WebExposureAlertsDashboard.json
  reflectiz/assets/dashboards/WebExposureRatingDashboard.json
  reflectiz/assets/logos/reflectiz_logo.svg
  reflectiz/assets/logos/reflectiz_logo_dark_mode.svg
  reflectiz/assets/logos/service_checks.json
  reflectiz/assets/logs/reflectiz.yaml
  reflectiz/assets/logs/reflectiz_tests.yaml
  reflectiz/assets/oauth_clients.json
  reflectiz/assets/service_checks.json
  reflectiz/images/dashboard_1.png
  reflectiz/images/dashboard_2.png
  reflectiz/manifest.json
  reflectiz/metadata.csv
Labels: editorial review, kind/technology-partner, agent/approved, docs/review-requested, product/approved, product/logos-complete, ecosystems/approved, assets/deploy-logs-staging

#2607 Update Redis Enterprise to set tls_verify to true by default in check code (ECOINT-109)
  redis_enterprise/CHANGELOG.md
  redis_enterprise/README.md
  redis_enterprise/assets/configuration/spec.yaml
  redis_enterprise/datadog_checks/redis_enterprise/__about__.py
  redis_enterprise/datadog_checks/redis_enterprise/check.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/defaults.py
  redis_enterprise/datadog_checks/redis_enterprise/config_models/instance.py
  redis_enterprise/datadog_checks/redis_enterprise/data/conf.yaml.example
  redis_enterprise/tests/support.py
  redis_enterprise/tests/test_redis_enterprise.py
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/review-requested

#2620 Update oauth_clients.json (ECOINT-130)
  adaptive_shield/assets/oauth_clients.json
Labels: kind/technology-partner, product/approved, ecosystems/approved

#2618 Fix README.md and update URL for screenshot image links. (ECOINT-128)
  cribl_stream/README.md
Labels: kind/technology-partner, docs/approved, product/approved, ecosystems/approved

#2623 Reflectiz integration fix facet reflectiz.alert.severity source (ECOINT-23)
  reflectiz/assets/logs/reflectiz.yaml
Labels: kind/technology-partner, product/approved, ecosystems/review-requested, assets/deploy-logs-staging

#2625 Reflectiz integration Metric Short Name Update
  reflectiz/metadata.csv
Labels: kind/technology-partner, product/approved, ecosystems/review-requested

#2624 Update auth0.yaml for additional messages
  auth0/assets/logs/auth0.yaml
  auth0/assets/logs/auth0_tests.yaml
Labels: kind/technology-partner, product/review-requested, ecosystems/review-requested, assets/deploy-logs-staging

#2546 Initial commit of Ocient integration (ECOINT-49)
  .codecov.yml
  .github/CODEOWNERS
  .github/workflows/test-all.yml
  ocient/CHANGELOG.md
  ocient/README.md
  ocient/assets/configuration/spec.yaml
  ocient/assets/dashboards/ocient_overview.json
  ocient/assets/service_checks.json
  ocient/datadog_checks/__init__.py
  ocient/datadog_checks/ocient/__about__.py
  ocient/datadog_checks/ocient/__init__.py
  ocient/datadog_checks/ocient/check.py
  ocient/datadog_checks/ocient/config_models/__init__.py
  ocient/datadog_checks/ocient/config_models/defaults.py
  ocient/datadog_checks/ocient/config_models/instance.py
  ocient/datadog_checks/ocient/config_models/shared.py
  ocient/datadog_checks/ocient/config_models/validators.py
  ocient/datadog_checks/ocient/data/conf.yaml.example
  ocient/datadog_checks/ocient/metrics.py
  ocient/hatch.toml
  ocient/images/ocient_dashboard.png
  ocient/images/ocient_logo.svg
  ocient/manifest.json
  ocient/metadata.csv
  ocient/pyproject.toml
  ocient/tests/__init__.py
  ocient/tests/common.py
  ocient/tests/conftest.py
  ocient/tests/docker/docker-compose.yaml
  ocient/tests/docker/vector.yaml
  ocient/tests/test_ocient.py
Labels: editorial review, kind/technology-partner, agent/approved, docs/approved, product/approved, product/logos-complete, ecosystems/approved

#2617 redis_enterprise - enforce metric types (ECOINT-132)
  redis_enterprise/README.md
  redis_enterprise/assets/dashboards/redis_enterprise_active-active.json
  redis_enterprise/assets/dashboards/redis_enterprise_database.json
  redis_enterprise/assets/dashboards/redis_enterprise_node.json
  redis_enterprise/assets/dashboards/redis_enterprise_overview.json
  redis_enterprise/assets/dashboards/redis_enterprise_proxy-threads.json
  redis_enterprise/assets/dashboards/redis_enterprise_shard.json
Labels: kind/technology-partner, agent/approved, docs/approved, product/approved, ecosystems/approved
